### ISSUE TITLE
Request for Comment: Adding ECLIPSE-Compatible Type Designators to `WellControls`

### ISSUE THREAD

**Issue by bska** [OPM/opm-simulators#1699] opened 2019-01-08 12:08 UTC
In my work on a ECLIPSE-compatible restart facility for Flow, I am in the process of finalising the ability to restart Flow from a strictly ECLIPSE-compatible restart file (see PR OPM/opm-common#548).  One of the remaining issues is that Flow's nonlinear solver appears to be somewhat sensitive to getting exactly correct active controls when restarting a simulation.  For instance, I have a case based on SPE1 that will perform two initial well iterations before converging to the appropriate active constraint for the producer when started in the middle of the history with an incorrect active constraint.  Those two well iterations appear to be enough for the final result to deviate appreciably from the result of running a complete simulation of the entire history.

While those symptoms are a little concerning in the long term, I am currently considering a work-around that will allow us to save a well's active constraint in the `IWEL` restart vector and restore it from there.  In particular, I am thinking about adding an ECLIPSE-compatible type designator into `struct WellControls` as follows:
```diff
diff --git a/opm/core/wells/well_controls.c b/opm/core/wells/well_controls.c
index 8a64c525..03ae280c 100644
--- a/opm/core/wells/well_controls.c
+++ b/opm/core/wells/well_controls.c
@@ -104,6 +104,11 @@ struct WellControls
      */
     double *distr;
 
+    /**
+     * Array of ECLIPSE-compatible control type designators
+     */
+    int *designator;
+
```
and then adding relevant accessor methods and constructor arguments as well as updating all callers accordingly.  The only reasonable designator values will be those from [`IWell::Value::WellCtrlMode`](https://github.com/OPM/opm-common/blob/85949d44accc0aab6188d7f15b10a99024121b50/opm/output/eclipse/VectorItems/well.hpp#L68-L88) so the member function `WellsManager::setupWellControls()` must become aware of those.  Finally I would like to repurpose or rename [`data::Well::control`](https://github.com/OPM/opm-common/blob/85949d44accc0aab6188d7f15b10a99024121b50/opm/output/data/Wells.hpp#L154) to contain these designator values rather than the return value of
```C
well_controls_get_current(wells->ctrls[i]);
```
which we currently output in [`RestartIO::save()`](https://github.com/OPM/opm-common/blob/85949d44accc0aab6188d7f15b10a99024121b50/src/opm/output/eclipse/RestartIO.cpp#L77-L90) when creating extended restart files.

I should hasten to add that I view this designator information as a bit of a hack, but I also think that it is a necessary stop-gap measure to enable high-fidelity restart of Flow from an ECLIPSE-compatible restart file.  I also think that saving and restoring this information will become easier if/when we start implementing the simulator in terms of [`Opm::Well`](https://github.com/OPM/opm-common/blob/85949d44accc0aab6188d7f15b10a99024121b50/opm/parser/eclipse/EclipseState/Schedule/Well.hpp#L52-L58) objects rather than the original [`Wells`](https://github.com/OPM/opm-simulators/blob/480fa1fd44ecbead7190c9684320ecf2b06910b5/opm/core/wells.h#L50) structure.

Any and all comments/questions are greatly appreciated.

**Comment by GitPaean** [comment] 2019-01-08 13:04
> One of the remaining issues is that Flow's nonlinear solver appears to be somewhat sensitive to getting exactly correct active controls when restarting a simulation.

Theoretically, when the results get converged with the correct reservoir state and the correct control, the results should be equivalent to some extend depending on the convergence tolerance. 

> For instance, I have a case based on SPE1 that will perform two initial well iterations before converging to the appropriate active constraint for the producer when started in the middle of the history with an incorrect active constraint.

It will be interesting how different the results are.  At the moment, if it begins with different control constraint, it will solve the well equation locally (means without updating the reservoir state.) to get converged first. I still think when it gets converged, the results should be comparable. If it get converged with different result, then there is some investigation needs to be done. 

Explicit quantities are the tricky part and can be the cause. If the calculation are based on different explicit quantities, they can get converged with different solution.  There are two explicit quantities. The important one is the perforation pressure difference, by definition based on the WellState from the end of last time step. We need the perforation rates and perforation pressures to calculate.

**Comment by GitPaean** [comment] 2019-01-09 11:47
> I am currently considering a work-around that will allow us to save a well's active constraint in the IWEL restart vector and restore it from there. 

I am not very familiar how the RESTART works.  I guess the `active constraint` is from the previous time step.  Will it be possible that the `active constraint` does not exist in the `well_controls` in the current time step?

**Comment by GitPaean** [comment] 2019-01-11 12:05
Some digging into this case SPECASE1 restart case, 

The very possible culprit is that when restarting, the IntensiveQuantities did not use the RS from the RESTART file, instead, it calculates a new one. 

The new one looks much bigger than the one from the RESTART file (1.27), the calculated one can be above 2, which causes the simulation restarts from a different state of the reservoir. 

The calling stack is as follows, 
```
Ewoms::BlackOilIntensiveQuantities<Ewoms::Properties::TTag::EclFlowProblem>::update blackoilintensivequantities.hh:214
Ewoms::FvBaseElementContext<Ewoms::Properties::TTag::EclFlowProblem>::updateSingleIntQuants_ fvbaseelementcontext.hh:586
Ewoms::FvBaseElementContext<Ewoms::Properties::TTag::EclFlowProblem>::updateIntensiveQuantities_ fvbaseelementcontext.hh:569
Ewoms::FvBaseElementContext<Ewoms::Properties::TTag::EclFlowProblem>::updatePrimaryIntensiveQuantities fvbaseelementcontext.hh:215
Ewoms::EclProblem<Ewoms::Properties::TTag::EclFlowProblem>::updateCompositionChangeLimits_ eclproblem.hh:1531
Ewoms::EclProblem<Ewoms::Properties::TTag::EclFlowProblem>::initialSolutionApplied eclproblem.hh:1338
Ewoms::FvBaseDiscretization<Ewoms::Properties::TTag::EclFlowProblem>::applyInitialSolution fvbasediscretization.hh:596
Opm::FlowMainEbos<Ewoms::Properties::TTag::EclFlowProblem>::setupEbosSimulator FlowMainEbos.hpp:426
Opm::FlowMainEbos<Ewoms::Properties::TTag::EclFlowProblem>::execute FlowMainEbos.hpp:213
Opm::flowEbosBlackoilMain flow_ebos_blackoil.cpp:59
main flow.cpp:259
__libc_start_main 0x00007fa83482b830
_start 0x000000000166c5d9```

Any suggestions, @andlaus , @atgeirr

**Comment by GitPaean** [comment] 2019-01-11 12:19
I still keep my original comments. When the state of the reservoir is the same, and we have the same group of control/constraint. Even we begin with different active control, when it gets converged, the result should be comparable. It should apply for most of the cases, while not ruling out some special corner situations.

**Comment by GitPaean** [comment] 2019-01-11 12:46
I have nothing against re-cording the current active well control, possibly required if we want "perfect" restart. 

The control index in WellState is not enough.

**Comment by bska** [comment] 2020-05-29 06:47
I'm closing this. It is no longer relevant since the type no longer exists.

**Closed** 2020-05-29 06:47 UTC
