### ISSUE TITLE
2019-04: Restart Runs Throw An Exception

### ISSUE THREAD

**Issue by OPMUSER** [OPM/opm-simulators#1849] opened 2019-05-18 01:26 UTC
OPM Flow will not run a restart case, either using the commercial simulator restart files or the OPM-Fow restart files. SPE1 test decks are attached.

Initially I thought this was because the "base run" was generated using 2018-10, but when I reran the "base run" with 2019-04 I get the same problem.

These decks ran okay under 2018-10.

[SPE1Case4-Restart.tar.gz](https://github.com/OPM/opm-simulators/files/3193504/SPE1Case4-Restart.tar.gz)

**Comment by GitPaean** [comment] 2019-05-18 18:49
Please refer to the discussion in https://github.com/OPM/opm-simulators/issues/1843 . 

If the symptom is the same as  https://github.com/OPM/opm-simulators/issues/1843 , then it got fixed through  https://github.com/OPM/opm-simulators/pull/1839 . 

It was broken sometime during March and April.

**Comment by OPMUSER** [comment] 2019-05-19 06:40
Don't know, did the fix make it into the 2019-04 release?

**Comment by GitPaean** [comment] 2019-05-19 16:20
The fix in #1839 is not included in the 2019-04 release.

**Comment by blattms** [comment] 2019-05-20 05:52
That is a (more than) a pity, then. I guess we whould think about making a bug-fix
release with the patch ASAP.

**Comment by OPMUSER** [comment] 2019-05-20 06:35
Can somebody test the files I uploaded to confirm that there is no problem with restarting using a version with the #1843 patch, first. Just to confirm that we already have a fix for this. I would do this myself, but it is beyond my skill set unfortunately.

If this works then we do need a bug fix release, if it does not then its back to the drawing board :-)

**Comment by GitPaean** [comment] 2019-05-20 06:59
It did not work. Your issue is the same with the issue reported in https://github.com/OPM/opm-simulators/issues/1828 . It is unsolved.

**Comment by OPMUSER** [comment] 2019-05-20 07:07
@GitPaean thanks for testing on pointing out the #1828 issue.

We need to fix this as it going to cause a lot more error reporting. And yes the commercial simulator does not allow the EQUIL etc. set of keywords in a restart run.

**Comment by GitPaean** [comment] 2019-05-20 07:12
You mentioned that it use to work under 2018-10 release, which means it is a regression. 

It can be a good news since it might be able to be fixed in a simpler manner.  

I think refactoring those related code might not be easy.

**Comment by OPMUSER** [comment] 2019-05-20 11:53
Yes it worked in 2018-10, so like you said this is a regression.

**Comment by GitPaean** [comment] 2019-05-31 07:28
I guess this should be closed together with #1828.

**Closed by GitPaean** 2019-05-31 07:28 UTC
