### ISSUE TITLE
The problem with oscillating behavior

### ISSUE THREAD

**Issue by dkolesnikov** [OPM/opm-simulators#1420] opened 2018-03-02 15:13 UTC
Dear OPM community,

I have launched OPM on the 3-phase 3D problems. The fragment of logs is below:
```
>#### Time step  450 at day 6084/10942, date = 29-Aug-2034
>####  Substep 0, stepsize 7.5881 days.
>####  Substep 0, stepsize 2.50407 days.
>####  Substep 0, stepsize 0.826344 days.
>####  Substep 0, stepsize 0.272694 days.
>####  Substep 0, stepsize 0.0899889 days.
>####    Oscillating behavior detected: Relaxation set to 0.900000
>####  Substep 0, stepsize 0.0296963 days.
>####    Oscillating behavior detected: Relaxation set to 0.900000
>####    Oscillating behavior detected: Relaxation set to 0.800000
>####  Substep 0, stepsize 0.00979979 days.
>####    Oscillating behavior detected: Relaxation set to 0.900000
>####  Substep 0, stepsize 0.00323393 days.
>####    Oscillating behavior detected: Relaxation set to 0.900000
>####  Substep 0, stepsize 0.0010672 days.
>####    Oscillating behavior detected: Relaxation set to 0.900000
>####    Oscillating behavior detected: Relaxation set to 0.800000
>####  Substep 0, stepsize 0.000352175 days.
>####  Substep 0, stepsize 0.000116218 days.
>####    Oscillating behavior detected: Relaxation set to 0.900000
>####    Oscillating behavior detected: Relaxation set to 0.800000
>####    Oscillating behavior detected: Relaxation set to 0.700000
>#### Error: Solver failed to converge after cutting timestep 10 times.
>#### Error: Program threw an exception: [/build/opm-simulators-OK8h8c/opm-simulators-2017.04-rfinal/opm/simulators/timestepping/AdaptiveTimeStepping_impl.hpp:348] Solver failed to converge after cutting timestep 10 times.
>#### -------------------------------------------------------
>#### Primary job  terminated normally, but 1 process returned a non-zero exit code. Per user-direction, the job has been aborted.
```
Logs with 3 different decks are [here](https://github.com/OPM/opm-simulators/files/1775579/Oscillation_problem_logs.zip). Which OPM solver parameters can I change to avoid such oscillations? 

Thank you in advance,
Denis, Ph.D. student in comp. maths

**Comment by GitPaean** [comment] 2018-03-08 13:00
Hi, the attached files do not have .compat and .wconfig file. 

And also, do you have any update from your side? Did you run the case with Eclipse?

**Comment by GitPaean** [comment] 2018-03-16 21:46
Since there is not the complete deck, we really could not reproduce the behavior and help you about this issue. This issue along with #1419, #1418 means something wrong happened during the simulation, either because of problem of flow or due to problem of the case setup. 

Closing this issue along with issue #1419, #1418 now. Feel free to reopen the issues or open new issues with updated information. We will be willing to help you to address the problem.

**Closed by GitPaean** 2018-03-16 21:46 UTC
