### ISSUE TITLE
Invalid FLO_TYPE error when using VFP table for gas lift

### ISSUE THREAD

**Issue by subhis** [OPM/opm-simulators#1598] opened 2018-10-19 16:16 UTC
Hello. I'm trying to run a case on flow, but have problems with gas lift. The model runs with no error  when no THP and artificial lift quantity is specified in WCONPROD section, but when gas lift is activated, I get the following error: 

```
Report step  1/3 at day 60/821, date = 05-Jan-1998

Time step 0, stepsize 60 days.
Time step summary: newton its =  4, linearizations =  5 ( 1.477 sec), linear its = 100 ( 2.727 sec)

Time step 1, stepsize 172.714 days.

Error: [/build/opm-simulators-Jqwb4p/opm-simulators-2018.04-rfinal/opm/autodiff/VFPHelpers.hpp:95] Invalid FLO_TYPE: '126233440'

Error: Program threw an exception: [/build/opm-simulators-Jqwb4p/opm-simulators-2018.04-rfinal/opm/autodiff/VFPHelpers.hpp:95] Invalid FLO_TYPE: '126233440'
```

The error can be reproduced by using attached schedule file on norne case: 
[SCH_VFP.SCH.gz](https://github.com/OPM/opm-simulators/files/2496561/SCH_VFP.SCH.gz)

Is this a known bug in the simulator or I'm doing something wrong? Appreciate your help.

**Comment by GitPaean** [comment] 2018-10-24 08:16
Sorry for the late response. I read the file briefly without seeing anything obviously wrong.

If you can provide (publicly or privately) the whole DECK file, so I can try to reproduce you problem, I might be able to give you an answer or fix.

**Comment by subhis** [comment] 2018-10-24 09:08
Please see the attached deck below: 
[norne_VFPPROD.zip](https://github.com/OPM/opm-simulators/files/2509763/norne_VFPPROD.zip)

**Comment by GitPaean** [comment] 2018-10-24 09:38
Hi, I do not have 2018.04 version of OPM by hand, but I tried to run it with the master branch. I did not see the problem you mentioned. Maybe it is something buggy has been fixed. 

We had a recent fix related to the ALQ (https://github.com/OPM/opm-common/pull/502), very likely that was the cause. 

To use this fix, either you can compile from the current master branch, or wait for a few days for the new release of 2018.10, which should be very soon (this week or next?) while I am not sure about the exact timeline. @joakim-hove is in charge of that.

**Comment by subhis** [comment] 2018-10-24 10:34
Guess I'll wait for the new version and check if it solves the problem. Thanks.

**Comment by GitPaean** [comment] 2018-10-24 11:02
> Guess I'll wait for the new version and check if it solves the problem. Thanks.

Please let us know how things go and feel free to close this issue if it works properly.

**Closed** 2018-10-26 10:04 UTC
