### ISSUE TITLE
flow_onephase_energy stop working

### ISSUE THREAD

**Issue by goncalvesmachadoc** [OPM/opm-simulators#2956] opened 2020-11-30 23:48 UTC
flow_onephase_energy is broken again. I am not able to figure out what change caused that/ what is the new issue. SPE1CASE2_THERMAL_ONEPHASE.DATA breaks at this point:

![image](https://user-images.githubusercontent.com/54812829/100678938-ab66eb00-336e-11eb-86e1-d0f4e7eda09a.png)

**Comment by atgeirr** [comment] 2020-12-01 07:45
I have now merged the PRs that dealt with one-phase stuff, please alert me if there are more. While it may not help with this (new) issue, it should be a little less hassle to work with.

**Comment by akva2** [comment] 2020-12-01 08:08
I cannot reproduce your particular failure mode, but I do get a memory issue.

In BlackoilOnePhaseIndices, waterSaturationIdx is set to -10000 https://github.com/OPM/opm-models/blob/master/opm/models/blackoil/blackoilonephaseindices.hh#L89. 

This get used for indexing in BlackOilNewtonMethod::updatePrimaryVariables_ https://github.com/OPM/opm-models/blob/master/opm/models/blackoil/blackoilnewtonmethod.hh#L233

**Closed** 2021-04-13 13:59 UTC
