### ISSUE TITLE
Errors when compiling with Eigen 3.3

### ISSUE THREAD

**Issue by einar90** [OPM/opm-simulators#751] opened 2016-07-05 07:33 UTC
I'm getting a build error when attempting to build with Eigen 3.3~beta1-2 on Ubuntu 16.04. I'm aware that you recommend using Eigen 3.1, but all libraries I've compiled up to this (common, core, material, output and parser) have compiled just fine with Eigen 3.3.

[Build log](https://gist.github.com/einar90/07c76d4df73ec7b60006fe7c1443283a)

**Comment by atgeirr** [comment] 2016-07-05 07:58
Thanks for noticing. There is indeed a change related to the index types as detailed here: http://eigen.tuxfamily.org/index.php?title=3.3#Index_typedef

I have not checked what the proper fix is: could you try replacing the typedef on line 190 with
```
        typedef typename Eigen::internal::remove_all<Lhs>::type::StorageIndex Index;
```
to see if that works? A proper fix should probably change the name of the typedef to StorageIndex as well, and there may be other places needing the same (not checked).

It is not so strange that the other modules did not complain: they do not use Eigen...

**Comment by einar90** [comment] 2016-07-05 08:23
Thanks for the quick reply. The change seems to fix the error. However, I'm now getting a different error: [build log](https://gist.github.com/einar90/1351b84ff66d4f5bbd8f509e28479474).

**Comment by atgeirr** [comment] 2016-07-05 08:52
I am not sure what the cause of that error is, if you don't need the polymer sims you can try disabling them as a workaround (comment out the relevant .cpp file entries in CMakeList_files.cmake).

About the first error (and second for that matter): if you can create a fix and make a pull request I'd be happy to merge it (assuming it does not ruin things for older Eigen versions)!

**Comment by einar90** [comment] 2016-07-05 09:23
I'll try to create a fix for the errors then, thanks for the help!

**Comment by akva2** [comment] 2016-07-05 09:28
the index type error can be fixed with an auto, but you will be bitten with what seemed to be a bug in eigen to me (attempt to call a private member deep down in eigen templates).

**Comment by einar90** [comment] 2016-07-05 11:28
I agree that the bug seems to be in Eigen. The are many fixes listed for similar/related issues in the [changelog](http://eigen.tuxfamily.org/index.php?title=ChangeLog#Eigen_3.3-beta2) for 3.3 beta2. I'll wait for that release (hopefully wont take too long seeing that beta1 is from december) and try to create a fix (if it's still needed) when that time comes.

Meanwhile, I've downgraded to Eigen 3.2.8, the most recent stable release, which seems to work fine.

**Comment by andlaus** [comment] 2017-04-07 10:35
I guess this been fixed so I'll close the issue for now. reopen if it still applies.

**Closed by andlaus** 2017-04-07 10:35 UTC
