### ISSUE TITLE
Broken tests - on my machine

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-simulators#1900] opened 2019-06-20 10:22 UTC
OK - instead of the venerable "works on my machine" I seem to have a "does not work on my machine" situation; looking at jenkins post-builders it seems that current master is all green in that department, but locally on my machine several tests fail:
```
39/59 Test #39: compareECLFiles_flow+3D_MSW .........................***Failed   24.28 sec
45/59 Test #45: compareECLFiles_flow+MSW_MODEL_1 ....................***Failed    4.00 sec
47/59 Test #47: compareECLFiles_flow+FAULTS_MODEL_1 .................***Failed    5.83 sec
39/59 Test #39: compareECLFiles_flow+3D_MSW .........................***Failed   24.28 sec
45/59 Test #45: compareECLFiles_flow+MSW_MODEL_1 ....................***Failed    4.00 sec
47/59 Test #47: compareECLFiles_flow+FAULTS_MODEL_1 .................***Failed    5.83 sec
```

I will post test output from the individual tests in separate comments.

**Comment by GitPaean** [comment] 2019-06-20 10:24
Yes. You can just post one of them, like 3D_MSW.   They are related to MSW.

**Comment by joakim-hove** [comment] 2019-06-20 10:25
**39: compareECLFiles_flow+3D_MSW**
```
Unified restart files, sequence  39
39: 
39: Comparing SEQNUM ...  done.
39: Comparing INTEHEAD ...  done.
39: Comparing LOGIHEAD ...  done.
39: Comparing DOUBHEAD ...  done.
39: Comparing IGRP ...  done.
39: Comparing SGRP ...  done.
39: Comparing XGRP ...  done.
39: Comparing ZGRP ...  done.
39: Comparing ISEG ...  done.
39: Comparing ILBS ...  done.
39: Comparing ILBR ...  done.
39: Comparing RSEG ...  done.
39: Comparing IWEL ...  done.
39: Comparing SWEL ...  done.
39: Comparing XWEL ...  done.
39: Comparing ZWEL ...  done.
39: Comparing ICON ...  done.
39: Comparing SCON ...  done.
39: Comparing XCON ...  done.
39: Comparing STARTSOL ...  done.
39: Comparing PRESSURE ...  done.
39: Comparing RS ...  done.
39: Comparing RV ...  done.
39: Comparing SGAS ...  done.
39: Comparing SWAT ...  done.
39: Comparing ENDSOL ...  done.
39:  
39: 4 keywords exhibit failures
39: 	RSEG: Restart, sequence 34
39: 		Fails for 7 entries
39: 		Largest absolute error: 1.0430594e-01
39: 		Largest relative error: 1.2305159e-05
39: 	XCON: Restart, sequence 34
39: 		Fails for 19 entries
39: 		Largest absolute error: 2.1683986e+00
39: 		Largest relative error: 1.6041495e-05
39: 	XGRP: Restart, sequence 34
39: 		Fails for 10 entries
39: 		Largest absolute error: 1.6228019e-01
39: 		Largest relative error: 1.4521960e-05
39: 	XWEL: Restart, sequence 34
39: 		Fails for 5 entries
39: 		Largest absolute error: 1.6228019e-01
39: 		Largest relative error: 1.4440218e-05
...
15 keywords exhibit failures
39: 	FOPP: Summary file
39: 		Fails for 1 entries
39: 		Largest absolute error: 8.7890625e-02
39: 		Largest relative error: 1.0394187e-05
39: 	FOPR: Summary file
39: 		Fails for 1 entries
39: 		Largest absolute error: 8.7890625e-02
39: 		Largest relative error: 1.0417227e-05
39: 	FVPR: Summary file
39: 		Fails for 1 entries
39: 		Largest absolute error: 1.6308594e-01
39: 		Largest relative error: 1.0645401e-05
39: 	FWPP: Summary file
39: 		Fails for 1 entries
39: 		Largest absolute error: 3.2470703e-02
39: 		Largest relative error: 1.4499388e-05
39: 	FWPR: Summary file
39: 		Fails for 1 entries
39: 		Largest absolute error: 3.2470703e-02
39: 		Largest relative error: 1.4456145e-05
39: 	GOPP:P: Summary file
39: 		Fails for 1 entries
39: 		Largest absolute error: 8.7890625e-02
39: 		Largest relative error: 1.0394187e-05
39: 	GOPR:P: Summary file
39: 		Fails for 1 entries
39: 		Largest absolute error: 8.7890625e-02
39: 		Largest relative error: 1.0417227e-05
39: 	GVPR:P: Summary file
39: 		Fails for 1 entries
39: 		Largest absolute error: 1.6308594e-01
39: 		Largest relative error: 1.0645401e-05
39: 	GWPP:P: Summary file
39: 		Fails for 1 entries
39: 		Largest absolute error: 3.2470703e-02
39: 		Largest relative error: 1.4499388e-05
39: 	GWPR:P: Summary file
39: 		Fails for 1 entries
39: 		Largest absolute error: 3.2470703e-02
39: 		Largest relative error: 1.4456145e-05
39: 	WOPP:PROD01: Summary file
39: 		Fails for 1 entries
39: 		Largest absolute error: 8.7890625e-02
39: 		Largest relative error: 1.0394187e-05
39: 	WOPR:PROD01: Summary file
39: 		Fails for 1 entries
39: 		Largest absolute error: 8.7890625e-02
39: 		Largest relative error: 1.0417227e-05
39: 	WVPR:PROD01: Summary file
39: 		Fails for 1 entries
39: 		Largest absolute error: 1.6308594e-01
39: 		Largest relative error: 1.0645401e-05
39: 	WWPP:PROD01: Summary file
39: 		Fails for 1 entries
39: 		Largest absolute error: 3.2470703e-02
39: 		Largest relative error: 1.4499388e-05
39: 	WWPR:PROD01: Summary file
39: 		Fails for 1 entries
39: 		Largest absolute error: 3.2470703e-02
39: 		Largest relative error: 1.4456145e-05
```

**Comment by totto82** [comment] 2019-06-20 10:25
These 3 tests always fails on my side as well.

**Comment by bska** [comment] 2019-06-20 10:25
> ```
> 39/59 Test #39: compareECLFiles_flow+3D_MSW .........................***Failed   24.28 sec
> 45/59 Test #45: compareECLFiles_flow+MSW_MODEL_1 ....................***Failed    4.00 sec
> 47/59 Test #47: compareECLFiles_flow+FAULTS_MODEL_1 .................***Failed    5.83 sec
> 39/59 Test #39: compareECLFiles_flow+3D_MSW .........................***Failed   24.28 sec
> 45/59 Test #45: compareECLFiles_flow+MSW_MODEL_1 ....................***Failed    4.00 sec
> 47/59 Test #47: compareECLFiles_flow+FAULTS_MODEL_1 .................***Failed    5.83 sec
> ```

Are each of the tests 39, 45, and 47 actually reported twice on your system or is that "just" a copy+paste issue?

**Comment by joakim-hove** [comment] 2019-06-20 10:25
> Are each of the tests 39, 45, and 47 actually reported twice on your system or is that "just" a copy+paste issue?

Hmmm - let me double check.

**Comment by GitPaean** [comment] 2019-06-20 10:26
We have discussed earlier.  Since about more than one week ago, something changed on the Jenkins side which made I could not reproduce the same testing results from Jenkins anymore.

**Comment by totto82** [comment] 2019-06-20 10:27
Could it be umfpack version related? Just a wild guess. Some more relaxed tolerances would be appreciated for these cases.

**Comment by bska** [comment] 2019-06-20 10:27
> These 3 tests always fails on my side as well.

On my system too (all configurations, i.e., release/debug, with and without Address Sanitizer, sequential/MPI).

**Comment by GitPaean** [comment] 2019-06-20 10:29
> On my system too (all configurations, i.e., release/debug, with and without Address Sanitizer, sequential/MPI).

Has always been this way, or it is something recent? To me, it is something since about two weeks ago.

**Comment by joakim-hove** [comment] 2019-06-20 10:30
>Are each of the tests 39, 45, and 47 actually reported twice on your system or is that "just" a copy+paste issue? 

I also wondered a bit - without checking - because the plain `ctest` output had 6 lines with errors - the ones I copy&pasted into the message, but the bottom of the ctest output showed "Three tests failed?" That might be a local issue on my side and beside the point - main issue is that the(?) three MSW tests fail on my machine, and seem to pass on jenkins? Could it be that they are not built on jenkins?

**Comment by joakim-hove** [comment] 2019-06-20 10:31
> Some more relaxed tolerances would be appreciated for these cases.

They all seem to fail with relative error just above 1e-5.

**Comment by joakim-hove** [comment] 2019-06-20 10:32
It gets really difficult to debug test failures in my code locally - when these test failures are overlayed.

**Comment by bska** [comment] 2019-06-20 10:34
> It gets really difficult to debug test failures in my code locally - when these test failures are overlayed.

The way I do it is keep and build an unmodified `master` of all modules.  If a test fails in a development branch I compare the results to that of the master branch.  It's expensive in terms of disk space and build time, but it avoids false positives.

**Comment by joakim-hove** [comment] 2019-06-20 10:37
> It's expensive in terms of disk space and build time

and most of all developer time ...

**Comment by GitPaean** [comment] 2019-06-20 10:41
Since some while before https://github.com/OPM/opm-common/pull/807 , we found this problem. 

Master branch got suddenly broken and we could not reproduce the failure locally.

**Comment by GitPaean** [comment] 2019-06-20 10:44
And with different version of DUNE, some two phase cases can also fail, which is expected due to the different implementation of function invert() for DenseMatrix (or DynamicMatrix).

**Comment by bska** [comment] 2019-06-20 10:47
> main issue is that the(?) three MSW tests fail on my machine, and seem to pass on jenkins? Could it be that they are not built on jenkins?

They are definitely built on the CI system.  If you review the [commit log](https://github.com/OPM/opm-tests/commits/master/msw_3d_hfa/opm-simulation-reference/flow/3D_MSW.UNRST) of the reference data for `3D_MSW.UNRST` you'll notice that almost all commits are made by Jenkins as part of `update_data`.  If the tests were not built on the CI system there would be no such commits.

**Comment by bska** [comment] 2019-06-20 10:49
> > [The tests fail on] my system too (all configurations, i.e., release/debug, with and without Address Sanitizer, sequential/MPI).
> 
> Has always been this way, or it is something recent? To me, it is something since about two weeks ago.

Much longer than two weeks.  I don't remember starting to notice the symptom, but it was definitely some time last year (2018).

**Comment by joakim-hove** [comment] 2019-06-20 10:51
> Much longer than two weeks. I don't remember starting to notice the symptom, but it was definitely some time last year (2018).

Well - then it is *really* time to get it out of the way. At least when investigating "legitmate" jenkins errors in one of relevant tests it becomes .... I think that is what I am doing right now.

**Comment by GitPaean** [comment] 2019-06-20 10:52
> Much longer than two weeks. 

Then that is different. I have been able to have the same testing results with Jenkins until two weeks ago.

**Comment by GitPaean** [comment] 2019-06-20 10:59
IMO, the comparison criteria of the results are pretty strict.  We might be able to relax the comparison tolerance a little bit to some extent similar to there is not visual difference.  The current tolerance is much stricter than visual inspection. Then we can ignore the numeric noise due to float point calculation.

**Comment by joakim-hove** [comment] 2019-06-20 11:01
But what can be the source of this discrepancy? My guess would be that it is a version difference in one of the (numerical) external dependencies. The list of dependencies - at the top of my head:

1. Boost
2. libecl
3. DUNE (does DUNE pull in other numerical dependencies directly?)
4. Suitesparse/umfpack
6. ???

I really think we should get to the bottom of this.

**Comment by totto82** [comment] 2019-06-20 11:06
As I said earlier I suspect 4, since it only hits MSW stuff

**Comment by joakim-hove** [comment] 2019-06-20 12:19
OK - so let's investigate that avenue - my box (Debian stable) has suitesparse version: 4.5.4

**Comment by GitPaean** [comment] 2019-06-20 12:22
libumfpack5.7.1

At we have the same symptom.

**Comment by totto82** [comment] 2019-06-20 13:22
I have the same versions as Kai.

**Comment by alfbr** [comment] 2019-06-20 13:32
> The way I do it is keep and build an unmodified master of all modules. If a test fails in a development branch I compare the results to that of the master branch.

This is not how it should be. Before we relax tolerances, it would be good to get a good picture. Something is causing the fluctuations in results. If any of you can help narrow down the source of the fluctuations, that is very helpful. For instance, can we conclude that it is related to umfpack versions? Maybe it is caused by numerical instabilities in the multisegment well code (if so, a more robust implementation may allow us to keep strict tolerances for the benefit of all)? It could also be the test-cases themselves that are numerically unstable, i.e., severe convergence issues.

**Comment by GitPaean** [comment] 2019-06-20 19:35
> Something is causing the fluctuations in results. 

The fluctuations are relatively small, like the one @joakim-hove posted, with 1.e-5 order margin, which is relatively natural considering we do not have a tighter convergence tolerance. We will not be able to see difference in the results visually.  But I agree, there is something fragile in the system. 

> For instance, can we conclude that it is related to umfpack versions?
 
`umfpack` is a valid guess, while I will not be surprised if it is not the cause. 


One thing should be noted is that many people involved in the discussion are producing consistent results , even we are using different systems and setups. Following the discussion in https://github.com/OPM/opm-common/pull/807 , I am producing identical results with @tskille . Probably, we are using different linux distribution, different version of compilers and probably different version of DUNE. 

The master branch got broken in a sudden way before https://github.com/OPM/opm-common/pull/807.  For most of us, the setups on our own system probably have not changed for some while (months, years). I have been producing consistent testing results with Jenkins until recently (a few days before https://github.com/OPM/opm-common/pull/807). To me, it is something changed on Jenkins that caused the consistence, while Jenkins was interrupted by malware at the time.

**Comment by GitPaean** [comment] 2019-06-21 08:31
With #1903, there is a little more information was revealed. 

The other MSW test case `2D_H__` also fails with the following verbose output
```
38: 2 keywords exhibit failures
38: 	RS: Restart, sequence 76
38: 		Fails for 2 entries
38: 		Largest absolute error: 4.1999817e-02
38: 		Largest relative error: 5.0669150e-04
38: 	RS: Restart, sequence 77
38: 		Fails for 2 entries
38: 		Largest absolute error: 1.3954163e-02
38: 		Largest relative error: 1.2681198e-04
```

And also SPE3CASE1 also failed, which also fails in the Jenkins test, https://ci.opm-project.org/job/opm-simulators-PR-builder/43/testReport/(root)/mpi/compareParallelSim_flow_SPE3CASE1/ . 

With exactly the same failure information
```
56: 2 keywords exhibit failures
56: 	OPM_XWEL: Restart, sequence 164
56: 		Fails for 1 entries
56: 		Largest absolute error: 6.8123813e+03
56: 		Largest relative error: 8.3797352e-04
56: 	XWEL: Restart, sequence 164
56: 		Fails for 1 entries
56: 		Largest absolute error: 9.8805238e-01
56: 		Largest relative error: 8.3797352e-04
```
Basically it means on Jenkins and locally, the results are digitally equivalent. 

It strengthens further the guess that only MSW related cases are producing digitially unequal results. 

Then `UMFPACK` is a stronger guess now.

**Comment by GitPaean** [comment] 2019-06-21 09:10
Tightening the comparison tolerance further in #1903 produces the same message (more tests fails, while with the same comparison result locally) with the above comment.

**Comment by blattms** [comment] 2019-06-21 12:00
Well I can imagine that comparing results between two systems can lead to differences. It is perfectly possible that results of different software versions are nearly the same on the same system (the jenkins runs are on the same machine, I guess) while there is a difference on another one.

Hence are you sure that your system is the same as the machine where the jenkins CI runner runs?

**Comment by GitPaean** [comment] 2019-06-21 12:52
> Hence are you sure that your system is the same as the machine where the jenkins CI runner runs?

I am sure they are different in some sense. When different systems produce the same results, I think it is perfectly okay.  And people hope that. 

Here the problem is that it use to be the case, then things changed for unclear reasons, which causes frustration, because it is not as convenient as before.

**Comment by blattms** [comment] 2019-06-21 13:39
Maybe there is an easy way to to reproduce the result of the update data jenkins call on the local system?
Like publishing the lastest collection of git hashes used in the triggered build. Maybe that is even already there somewhere.

**Comment by bska** [comment] 2022-05-20 20:55
I'm closing this now.  It's unlikely that we'll ever resolve this problem fully.

**Closed by bska** 2022-05-20 20:55 UTC
