### ISSUE TITLE
Failing regression tests

### ISSUE THREAD

**Issue by joakim-hove** [OPM/opm-simulators#2323] opened 2020-02-07 07:26 UTC
The following tests fail on my machine:
```
The following tests FAILED:
	 37 - compareECLFiles_flow+3D_MSW (Failed)
	 38 - compareECLFiles_flow+2D_OILWATER_POLYMER (Failed)
	 40 - compareECLFiles_flow+2D_THREEPHASE_POLY_HETER (Failed)
	 43 - compareECLFiles_flow+MSW_MODEL_1 (Failed)
	 45 - compareECLFiles_flow+FAULTS_MODEL_1 (Failed)
	 57 - compareECLFiles_flow+TEST_WSEGSICD (Failed)
```
gcc: 8.3.0
dune: 2.6.0 
boost: 1.67
debian: 10.2
Processor: amd

**Comment by bska** [comment] 2020-02-07 07:50
> The following tests fail on my machine:

I can't tell at a glance. Is this roughly the same set of test failures as in the earlier report #1900?

**Comment by joakim-hove** [comment] 2020-02-07 07:59
> Is this roughly the same set of test failures as in the earlier report #1900?

There is overlap - but no the list is not identical.

**Comment by alfbr** [comment] 2020-02-07 08:08
Yes, it seems to be much of the same. One more test involving MSW wells which is new since then, and then a couple of polymer related tests. My comment back then still stands:

This is not how it should be. Before we relax tolerances (or disable the tests), it would be good to get a good picture. Something is causing the fluctuations in results. If any of you can help narrow down the source of the fluctuations, that is very helpful.

First up, does anyone see other tests failing, or is this the set of tests we can focus on?
Second, are any of these cases seeing convergence issues when they fail?
Third, are these tests failing consistently on your system?

**Comment by tskille** [comment] 2020-02-07 08:44
Following tests fails on my machine: 

         37 - compareECLFiles_flow+3D_MSW (Failed)
         43 - compareECLFiles_flow+MSW_MODEL_1 (Failed)
         45 - compareECLFiles_flow+FAULTS_MODEL_1 (Failed)
         57 - compareECLFiles_flow+TEST_WSEGSICD (Failed)

gcc: 7.3.1
dune: 2.6.0
boost: 1.69
rh7
Processor: intel

**Comment by totto82** [comment] 2020-02-07 08:44
Polymer go through on my machine. 	
```
 37 - compareECLFiles_flow+3D_MSW (Failed)
 43 - compareECLFiles_flow+MSW_MODEL_1 (Failed)
 45 - compareECLFiles_flow+FAULTS_MODEL_1 (Failed)
 57 - compareECLFiles_flow+TEST_WSEGSICD (Failed)
```
ubuntu:16.04
dune: 2.5
processor: i7-6700

**Comment by GitPaean** [comment] 2020-02-07 08:46
Dune version might have some impact on the MSW and Polymer results, because the different implementation of the inversion algorithms.

**Comment by alfbr** [comment] 2020-02-07 08:49
> Dune version might have some impact 

I doubt that is the cause. Jenkins, Joakim and Torbjørn all use the same Dune version.

@GitPaean are you seeing the same failures?

**Comment by GitPaean** [comment] 2020-02-07 08:55
on my machine
```
The following tests FAILED:
	 37 - compareECLFiles_flow+3D_MSW (Failed)
	 38 - compareECLFiles_flow+2D_OILWATER_POLYMER (Failed)
	 39 - compareECLFiles_flow+2D_POLYMER_INJECTIVITY (Failed)
	 40 - compareECLFiles_flow+2D_THREEPHASE_POLY_HETER (Failed)
	 41 - compareECLFiles_flow+SPE5CASE1 (Failed)
	 43 - compareECLFiles_flow+MSW_MODEL_1 (Failed)
	 45 - compareECLFiles_flow+FAULTS_MODEL_1 (Failed)
	 57 - compareECLFiles_flow+TEST_WSEGSICD (Failed)
Errors while running CTest
```

Ubuntu 19.10
gcc 9.2.1
dune 2.6.0

> @GitPaean are you seeing the same failures?

From about two years ago, I could not have totally same results with Jenkins anymore.  There have been always a few tests failed. 

It is possible for other tests that are not claimed to be failed, it is possible there is still some small difference in the residual history, while the results is within the tolerance. 

Not I remember there was something change in the Jenkins setup that made me no way (changing versions of dune, compiler versions, etc.) to get the exactly same residual history anymore. Not sure what was that.   I remember there was some virus impacts the Jenkins system and some fixed was done to Jenkins.

**Comment by GitPaean** [comment] 2020-02-07 08:58
Testing failure message for SPE5CASE1,  I think it should not really matter much. 

```
41: 48 keywords exhibit failures
41: 	DOUBHEAD: Restart, sequence 133
41: 		Fails for 1 entries
41: 		Largest absolute error: 1.5958939e-04
41: 		Largest relative error: 1.7950700e-06
41: 	DOUBHEAD: Restart, sequence 139
41: 		Fails for 1 entries
41: 		Largest absolute error: 3.3858322e-04
41: 		Largest relative error: 3.8445284e-06
41: 	DOUBHEAD: Restart, sequence 145
41: 		Fails for 1 entries
41: 		Largest absolute error: 2.5001736e-03
41: 		Largest relative error: 4.1702421e-05
41: 	DOUBHEAD: Restart, sequence 146
41: 		Fails for 1 entries
41: 		Largest absolute error: 1.5679324e-03
41: 		Largest relative error: 2.1222175e-05
41: 	DOUBHEAD: Restart, sequence 153
41: 		Fails for 1 entries
41: 		Largest absolute error: 1.9317789e-04
41: 		Largest relative error: 2.3300813e-06
41: 	DOUBHEAD: Restart, sequence 154
41: 		Fails for 1 entries
41: 		Largest absolute error: 1.5472134e-04
41: 		Largest relative error: 2.0171623e-06
41: 	DOUBHEAD: Restart, sequence 155
41: 		Fails for 1 entries
41: 		Largest absolute error: 2.9156643e-04
41: 		Largest relative error: 4.1003132e-06
41: 	DOUBHEAD: Restart, sequence 156
41: 		Fails for 1 entries
41: 		Largest absolute error: 4.3787530e-04
41: 		Largest relative error: 6.3101959e-06
41: 	DOUBHEAD: Restart, sequence 157
41: 		Fails for 1 entries
41: 		Largest absolute error: 1.6514491e-03
41: 		Largest relative error: 2.0500837e-05
41: 	DOUBHEAD: Restart, sequence 169
41: 		Fails for 1 entries
41: 		Largest absolute error: 2.6323857e-04
41: 		Largest relative error: 3.7968274e-06
41: 	DOUBHEAD: Restart, sequence 170
41: 		Fails for 1 entries
41: 		Largest absolute error: 1.5845639e-04
41: 		Largest relative error: 2.0512504e-06
41: 	DOUBHEAD: Restart, sequence 171
41: 		Fails for 1 entries
41: 		Largest absolute error: 1.0416481e-04
41: 		Largest relative error: 1.1326854e-06
41: 	DOUBHEAD: Restart, sequence 178
41: 		Fails for 1 entries
41: 		Largest absolute error: 6.8546549e-03
41: 		Largest relative error: 8.8250193e-05
41: 	DOUBHEAD: Restart, sequence 179
41: 		Fails for 1 entries
41: 		Largest absolute error: 2.0355478e-03
41: 		Largest relative error: 2.7472752e-05
41: 	DOUBHEAD: Restart, sequence 180
41: 		Fails for 1 entries
41: 		Largest absolute error: 3.4441706e-03
41: 		Largest relative error: 4.7043409e-05
41: 	DOUBHEAD: Restart, sequence 181
41: 		Fails for 1 entries
41: 		Largest absolute error: 7.8078106e-04
41: 		Largest relative error: 1.0215691e-05
41: 	DOUBHEAD: Restart, sequence 190
41: 		Fails for 1 entries
41: 		Largest absolute error: 1.2889230e-03
41: 		Largest relative error: 1.4362947e-05
41: 	DOUBHEAD: Restart, sequence 191
41: 		Fails for 1 entries
41: 		Largest absolute error: 8.5654488e-04
41: 		Largest relative error: 1.0559325e-05
41: 	DOUBHEAD: Restart, sequence 192
41: 		Fails for 1 entries
41: 		Largest absolute error: 2.9301264e-02
41: 		Largest relative error: 3.7258661e-04
41: 	DOUBHEAD: Restart, sequence 193
41: 		Fails for 1 entries
41: 		Largest absolute error: 6.6205705e-03
41: 		Largest relative error: 9.5788949e-05
41: 	DOUBHEAD: Restart, sequence 194
41: 		Fails for 1 entries
41: 		Largest absolute error: 2.4377348e-03
41: 		Largest relative error: 3.3595468e-05
41: 	DOUBHEAD: Restart, sequence 195
41: 		Fails for 1 entries
41: 		Largest absolute error: 8.3587912e-05
41: 		Largest relative error: 1.0034354e-06
41: 	DOUBHEAD: Restart, sequence 196
41: 		Fails for 1 entries
41: 		Largest absolute error: 1.2438336e-04
41: 		Largest relative error: 1.4688910e-06
41: 	DOUBHEAD: Restart, sequence 201
41: 		Fails for 1 entries
41: 		Largest absolute error: 8.4647223e-03
41: 		Largest relative error: 9.6061743e-05
41: 	DOUBHEAD: Restart, sequence 202
41: 		Fails for 1 entries
41: 		Largest absolute error: 1.8593564e-03
41: 		Largest relative error: 2.3497442e-05
41: 	DOUBHEAD: Restart, sequence 203
41: 		Fails for 1 entries
41: 		Largest absolute error: 9.3876380e-04
41: 		Largest relative error: 1.2195839e-05
41: 	DOUBHEAD: Restart, sequence 204
41: 		Fails for 1 entries
41: 		Largest absolute error: 1.2044651e-03
41: 		Largest relative error: 1.5284132e-05
41: 	DOUBHEAD: Restart, sequence 205
41: 		Fails for 1 entries
41: 		Largest absolute error: 6.4409343e-04
41: 		Largest relative error: 8.4036466e-06
41: 	DOUBHEAD: Restart, sequence 215
41: 		Fails for 1 entries
41: 		Largest absolute error: 1.5124047e-03
41: 		Largest relative error: 1.8740312e-05
41: 	DOUBHEAD: Restart, sequence 216
41: 		Fails for 1 entries
41: 		Largest absolute error: 2.3277739e-03
41: 		Largest relative error: 2.8033407e-05
41: 	DOUBHEAD: Restart, sequence 217
41: 		Fails for 1 entries
41: 		Largest absolute error: 7.8164805e-05
41: 		Largest relative error: 1.1630133e-06
41: 	DOUBHEAD: Restart, sequence 218
41: 		Fails for 1 entries
41: 		Largest absolute error: 1.6490070e-04
41: 		Largest relative error: 2.2960498e-06
41: 	DOUBHEAD: Restart, sequence 219
41: 		Fails for 1 entries
41: 		Largest absolute error: 5.2821042e-04
41: 		Largest relative error: 6.4887925e-06
41: 	DOUBHEAD: Restart, sequence 220
41: 		Fails for 1 entries
41: 		Largest absolute error: 3.9949827e-04
41: 		Largest relative error: 4.7243456e-06
41: 	DOUBHEAD: Restart, sequence 221
41: 		Fails for 1 entries
41: 		Largest absolute error: 1.2495566e-03
41: 		Largest relative error: 1.3485830e-05
41: 	DOUBHEAD: Restart, sequence 226
41: 		Fails for 1 entries
41: 		Largest absolute error: 1.2548254e-03
41: 		Largest relative error: 1.5781311e-05
41: 	DOUBHEAD: Restart, sequence 227
41: 		Fails for 1 entries
41: 		Largest absolute error: 2.4258457e-04
41: 		Largest relative error: 3.0023497e-06
41: 	DOUBHEAD: Restart, sequence 228
41: 		Fails for 1 entries
41: 		Largest absolute error: 6.5146794e-04
41: 		Largest relative error: 8.0176212e-06
41: 	DOUBHEAD: Restart, sequence 229
41: 		Fails for 1 entries
41: 		Largest absolute error: 4.8262008e-04
41: 		Largest relative error: 6.0340910e-06
41: 	DOUBHEAD: Restart, sequence 240
41: 		Fails for 1 entries
41: 		Largest absolute error: 2.0081223e-03
41: 		Largest relative error: 2.2702358e-05
41: 	DOUBHEAD: Restart, sequence 241
41: 		Fails for 1 entries
41: 		Largest absolute error: 4.5348357e-04
41: 		Largest relative error: 6.8624131e-06
41: 	DOUBHEAD: Restart, sequence 242
41: 		Fails for 1 entries
41: 		Largest absolute error: 3.3017563e-04
41: 		Largest relative error: 4.5569298e-06
41: 	DOUBHEAD: Restart, sequence 243
41: 		Fails for 1 entries
41: 		Largest absolute error: 1.0454600e-04
41: 		Largest relative error: 1.2533454e-06
41: 	DOUBHEAD: Restart, sequence 244
41: 		Fails for 1 entries
41: 		Largest absolute error: 4.3472591e-04
41: 		Largest relative error: 4.9958042e-06
41: 	DOUBHEAD: Restart, sequence 250
41: 		Fails for 1 entries
41: 		Largest absolute error: 1.9231016e-04
41: 		Largest relative error: 2.2872900e-06
41: 	DOUBHEAD: Restart, sequence 251
41: 		Fails for 1 entries
41: 		Largest absolute error: 3.8458172e-04
41: 		Largest relative error: 4.7419618e-06
41: 	DOUBHEAD: Restart, sequence 253
41: 		Fails for 1 entries
41: 		Largest absolute error: 5.0893083e-04
41: 		Largest relative error: 6.3177746e-06
41: 	DOUBHEAD: Restart, sequence 264
41: 		Fails for 1 entries
41: 		Largest absolute error: 3.4564977e-04
41: 		Largest relative error: 3.5461283e-06
41: 
41: Loading summary file /home/kaib/OPM-master-test/debug/opm-simulators/../opm-tests/spe5/opm-simulation-reference/flow/SPE5CASE1.SMSPEC  .... done
41: 
41: Loading summary file /home/kaib/OPM-master-test/debug/opm-simulators-build/tests/results/flow+spe5/SPE5CASE1.SMSPEC  .... done
41: 
41: Comparing summary files 
41: 
41: Checking 40  vectors  ...  done.
41: 
41: !Warning, rft files not found, hence not compared. 
41: 
41: 
41: Program finished 
41: 
1/1 Test #41: compareECLFiles_flow+SPE5CASE1 ...***Failed    3.96 sec

```

**Comment by tskille** [comment] 2020-02-07 09:08
> Testing failure message for SPE5CASE1, I think it should not really matter much.
> 
> ```
> 41: 48 keywords exhibit failures
> 41: 	DOUBHEAD: Restart, sequence 133
> 41: 		Fails for 1 entries
> 41: 		Largest absolute error: 1.5958939e-04
> 41: 		Largest relative error: 1.7950700e-06
41: compareECLFiles_flow+SPE5CASE1 ...***Failed    3.96 sec
> ```

This is most likely doubhead[1] (second item in doubhead). I have earlier suggested to remove this item from the testing (small fix in compareECL). DOUBHEAD is tested with strict tolerances (relative error of 1e-6) since this is static data (not dependent of simulation results). However this is not true for the second item in DOUBHEAD which is related to "next timestep"

**Comment by tskille** [comment] 2020-02-07 09:11
Regarding 

 37 - compareECLFiles_flow+3D_MSW (Failed)

Failing on summary and restart. increasing relative error from 1e-5 to 2e-5 is sufficient for this test on my machine

**Comment by tskille** [comment] 2020-02-07 09:32
Regarding 

43 - compareECLFiles_flow+MSW_MODEL_1 (Failed)

summary and restart fails.  

for summary file, needs to increase relative error from 1e-5 to 5e-3

  Keyword: RWPR:1, origin Summary file 
  
  Value index                 = 5
  (first value, second value) = (608.39, 605.582)

For restart file, need to increase absolute tolerance from 1e-5 to 2e-2

Comparing XCON ... 

  Keyword: XCON, origin Restart, sequence 12

 Value index                 = 1800
 (first value, second value) = (-146.191, -143.693)

This have larger errors, may be we should try to focus on this test ?

**Comment by joakim-hove** [comment] 2020-02-07 09:35
> Second, are any of these cases seeing convergence issues when they fail?

This is a bit outside my competence - but from a glance it looks like: "No convergence issues"

> Third, are these tests failing consistently on your system?

Yes - they are failing consistently.

**Comment by akva2** [comment] 2020-02-07 09:37
you should go at this from the other side. we need to tighten convergence criteria, not loosen comparison tolerances.

**Comment by GitPaean** [comment] 2020-02-07 09:44
> you should go at this from the other side. we need to tighten convergence criteria, not loosen comparison tolerances.

I think it is correct to do so. Maybe we should begin with evaluating the performance impact on always checking the CNV convergence.  Currently, we do not check it anymore after 8th Newton iteration.

**Comment by alfbr** [comment] 2020-02-07 09:48
> Maybe we should begin with evaluating the performance impact on always checking the CNV convergence. Currently, we do not check it anymore after 8th Newton iteration.

Please indicate if you are seeing this in your failures. As I asked initially, do you see convergence issues? More specifically, for which of the failing test-cases on your machine do you see more than eight Newton iterations as a possible cause?

**Comment by GitPaean** [comment] 2020-02-07 09:54
> Please indicate if you are seeing this in your failures. As I asked initially, do you see convergence issues? More specifically, for which of the failing test-cases on your machine do you see more than eight Newton iterations as a possible cause?

Okay. Now I see it is a separate issue and I might misunderstand @akva2 's comment.  
This issue is about the regression test. I still think @akva2 's suggestion is sensible and worth trying. I mean, for the regression test, we use tighter convergence tolerance to see whether it helps us to get more consistent testing results across different machines.

**Comment by alfbr** [comment] 2020-02-07 10:09
@GitPaean please answer my question, have you checked the PRT file to see if there are convergence issues on your failures, i.e., if you see test-cases where more than eight Newton iterations are needed on your machine.

**Comment by bska** [comment] 2020-02-07 10:16
> Comparing XCON ...
> 
> Keyword: XCON, origin Restart, sequence 12
> 
> Value index = 1800
> (first value, second value) = (-146.191, -143.693)

Just for context, in the MSW_MODEL_1 simulation deck XCON value index 1800 corresponds to

* Item 3 (Index 2 [`GasRate`](https://github.com/OPM/opm-common/blob/b57a4a39a390a2f10777a8909b435824cdfcec47/opm/output/eclipse/VectorItems/connection.hpp#L68)) of
* [Connection 2](https://github.com/OPM/opm-tests/blob/bf6ca66025e9516d7acb73a051db7b1f6f28e5d5/model1/include/history_msw.sch#L108) of
* [Well 3](https://github.com/OPM/opm-tests/blob/bf6ca66025e9516d7acb73a051db7b1f6f28e5d5/model1/include/history_msw.sch#L102)&mdash;PROD-3

**Comment by GitPaean** [comment] 2020-02-07 10:35
>  if you see test-cases where more than eight Newton iterations are needed on your machine.

I can not say I checked in high details for all the cases, while it is something I found just now.

	 39 - compareECLFiles_flow+2D_POLYMER_INJECTIVITY (Failed)
         40 - compareECLFiles_flow+2D_THREEPHASE_POLY_HETER (Failed)

The above two cases have chopped time step and requires more than 8 iterations to converge.

         38 - compareECLFiles_flow+2D_OILWATER_POLYMER (Failed) 
This one does not chop time step and requires more than 8 iterations to converge some time steps. 

I guess more iterations happens when we begin polymer injection. 


	 41 - compareECLFiles_flow+SPE5CASE1 (Failed)
This one has one time step chopped and multiple time steps converge at exactly 8 iterations, which is the most alarming symptoms related our CNV criteria checking strategy.

**Comment by tskille** [comment] 2020-02-07 11:50
I have now created a PR for skipping second item when comparing DOUBHEAD

  https://github.com/OPM/opm-common/pull/1453

**Comment by tskille** [comment] 2020-02-07 12:12
4 test failing on my machine 

37 - compareECLFiles_flow+3D_MSW (Failed)
43 - compareECLFiles_flow+MSW_MODEL_1 (Failed)
45 - compareECLFiles_flow+FAULTS_MODEL_1 (Failed)
57 - compareECLFiles_flow+TEST_WSEGSICD (Failed)

None of these have convergence issues as far as I can see.      
   
   37 - maximum number of newton its: 4
   43 - maximum number of newton its: 5
   45 - maximum number of newton its: 5
   57 - maximum number of newton its: 7

which means that all timesteps have converted before reaching default value of max-strict-iter

--max-strict-iter=INTEGER     Maximum number of Newton iterations before relaxed tolerances are used for the CNV convergence criterion. Default: 8

**Comment by alfbr** [comment] 2020-02-07 13:01
> None of these have convergence issues as far as I can see.

Still, at least one of them has large deviations. This probably boils down to two possible reasons:
-the MSW code is unstable
-the test-cases are unstable

Since the problem is across multiple cases, I believe it is the former. Maybe somebody familiar with the MSW code can help us test this by tightening some of the MSW internal convergence criteria, and see if that removes the failures?

**Comment by alfbr** [comment] 2020-02-07 13:04
>  39 - compareECLFiles_flow+2D_POLYMER_INJECTIVITY (Failed)
>      40 - compareECLFiles_flow+2D_THREEPHASE_POLY_HETER (Failed)
> ```
> 
> The above two cases have chopped time step and requires more than 8 iterations to converge.

Which probably means that the numerics is poorly implemented for polymer. This might be hard to solve. One possible quick fix is to tighten tolerances for these particular tests, e.g., allow more strict iterations than eight to ensure that we do not get bogous results as reference. Long term, I believe we should fix the numerical stability of the polymer implementation though.

**Comment by alfbr** [comment] 2020-02-10 14:20
@GitPaean I have now tested on the two polymer cases, trying to reproduce your failures. I am unsuccessful. Even with far stricter tolerances, they both run through fine. I did encounter a fall-out on the threading code though, which needed @dr-robertk fix in #2325 Please try the PR and see if they run through at your end.

**Comment by GitPaean** [comment] 2020-02-10 14:25
Thanks for the reporting. 

> Even with far stricter tolerances, they both run through fine. 

It probably means on your platform, you obtained bit-wise equivalent results with the reference results from Jenkins. 

>  Please try the PR and see if they run through at your end.

I will do that and report back.

**Comment by GitPaean** [comment] 2020-02-10 15:57
With #2325, the test failure related to `38 - compareECLFiles_flow+2D_OILWATER_POLYMER (Failed)
` is gone, while the other six remains. 
```
	 37 - compareECLFiles_flow+3D_MSW (Failed)
	 39 - compareECLFiles_flow+2D_POLYMER_INJECTIVITY (Failed)
	 40 - compareECLFiles_flow+2D_THREEPHASE_POLY_HETER (Failed)
	 43 - compareECLFiles_flow+MSW_MODEL_1 (Failed)
	 45 - compareECLFiles_flow+FAULTS_MODEL_1 (Failed)
	 57 - compareECLFiles_flow+TEST_WSEGSICD (Failed)
```

Not totally sure it was due to the update of the reference result from opm-tests or #2325 .

**Comment by GitPaean** [comment] 2020-02-10 16:03
Following the message above, the fix of `38 - compareECLFiles_flow+2D_OILWATER_POLYMER (Failed)` is mostly due to the update the reference results in jenkins. 

I am not totally sure about the details of the jenkins system update, it looks like it provide more similar result to my current system, which is pretty new.

**Comment by alfbr** [comment] 2020-02-10 16:42
@GitPaean maybe we can do a hangout, and try to figure out the next step together?

**Comment by GitPaean** [comment] 2020-02-11 10:40
> @GitPaean maybe we can do a hangout, and try to figure out the next step together?

@alfbr , sure. I will send you an email.

**Comment by blattms** [comment] 2020-09-10 06:08
I have local some failing tests while on jenkins all succeed.

**Comment by alfbr** [comment] 2020-09-10 07:59
> I have local some failing tests while on jenkins all succeed.

Please list which ones. Actually, we never got all multi-segment wells tests fixed for local testing.

**Comment by blattms** [comment] 2020-09-10 09:30
At least some of them might be unrelated to MSW (this is wth DUNE master):
```
81% tests passed, 23 tests failed out of 118

Total Test time (real) = 466.09 sec


The following tests FAILED:
         38 - compareECLFiles_flow+3D_MSW (Failed)
         40 - compareECLFiles_flow+2D_POLYMER_INJECTIVITY (Failed)
         42 - compareECLFiles_flow+SPE5CASE1 (Failed)
         49 - compareECLFiles_flow+0A1_GRCTRL_LRAT_ORAT_BASE_MODEL2_MSW (Failed)
         51 - compareECLFiles_flow+0A2_GRCTRL_LRAT_ORAT_GGR_BASE_MODEL2_MSW (Failed)
         53 - compareECLFiles_flow+0A3_GRCTRL_LRAT_LRAT_BASE_MODEL2_MSW (Failed)
         55 - compareECLFiles_flow+0A4_GRCTRL_LRAT_LRAT_GGR_BASE_MODEL2_MSW (Failed)
         70 - compareECLFiles_flow+9_1A_DEPL_MAX_RATE_MIN_BHP_MSW (Failed)
         72 - compareECLFiles_flow+9_1B_DEPL_MAX_RATE_MIN_THP_MSW (Failed)
         74 - compareECLFiles_flow+9_2A_DEPL_GCONPROD_1L_MSW (Failed)
         76 - compareECLFiles_flow+9_2B_DEPL_GCONPROD_2L_MSW (Failed)
         78 - compareECLFiles_flow+9_3A_GINJ_REIN-G_MSW (Failed)
         80 - compareECLFiles_flow+9_3B_GINJ_GAS_EXPORT_MSW (Failed)
         82 - compareECLFiles_flow+9_3C_GINJ_GAS_GCONSUMP_MSW (Failed)
         84 - compareECLFiles_flow+9_3D_GINJ_GAS_MAX_EXPORT_MSW (Failed)
         86 - compareECLFiles_flow+9_3E_GAS_MIN_EXPORT_MSW (Failed)
         88 - compareECLFiles_flow+9_4A_WINJ_MAXWRATES_MAXBHP_GCONPROD_1L_MSW (Failed)
         90 - compareECLFiles_flow+9_4B_WINJ_VREP-W_MSW (Failed)
         92 - compareECLFiles_flow+9_4C_WINJ_GINJ_VREP-W_REIN-G_MSW (Failed)
         94 - compareECLFiles_flow+9_4D_WINJ_GINJ_GAS_EXPORT_MSW (Failed)
         95 - compareECLFiles_flow+MOD4_GRP (Failed)
         96 - compareECLFiles_flow+MOD4_UDQ_ACTIONX (Failed)
         97 - compareECLFiles_flow+TEST_WSEGSICD (Failed)
Errors while running CTest
```

If I use DUNE 2.6 it is 2 less failing tests (SPE5CASE1, 2D_POLYMER_INJECTIVITY):
```
82% tests passed, 21 tests failed out of 118

Total Test time (real) = 439.87 sec

The following tests FAILED:
         38 - compareECLFiles_flow+3D_MSW (Failed)
         49 - compareECLFiles_flow+0A1_GRCTRL_LRAT_ORAT_BASE_MODEL2_MSW (Failed)
         51 - compareECLFiles_flow+0A2_GRCTRL_LRAT_ORAT_GGR_BASE_MODEL2_MSW (Failed)
         53 - compareECLFiles_flow+0A3_GRCTRL_LRAT_LRAT_BASE_MODEL2_MSW (Failed)
         55 - compareECLFiles_flow+0A4_GRCTRL_LRAT_LRAT_GGR_BASE_MODEL2_MSW (Failed)
         70 - compareECLFiles_flow+9_1A_DEPL_MAX_RATE_MIN_BHP_MSW (Failed)
         72 - compareECLFiles_flow+9_1B_DEPL_MAX_RATE_MIN_THP_MSW (Failed)
         74 - compareECLFiles_flow+9_2A_DEPL_GCONPROD_1L_MSW (Failed)
         76 - compareECLFiles_flow+9_2B_DEPL_GCONPROD_2L_MSW (Failed)
         78 - compareECLFiles_flow+9_3A_GINJ_REIN-G_MSW (Failed)
         80 - compareECLFiles_flow+9_3B_GINJ_GAS_EXPORT_MSW (Failed)
         82 - compareECLFiles_flow+9_3C_GINJ_GAS_GCONSUMP_MSW (Failed)
         84 - compareECLFiles_flow+9_3D_GINJ_GAS_MAX_EXPORT_MSW (Failed)
         86 - compareECLFiles_flow+9_3E_GAS_MIN_EXPORT_MSW (Failed)
         88 - compareECLFiles_flow+9_4A_WINJ_MAXWRATES_MAXBHP_GCONPROD_1L_MSW (Failed)
         90 - compareECLFiles_flow+9_4B_WINJ_VREP-W_MSW (Failed)
         92 - compareECLFiles_flow+9_4C_WINJ_GINJ_VREP-W_REIN-G_MSW (Failed)
         94 - compareECLFiles_flow+9_4D_WINJ_GINJ_GAS_EXPORT_MSW (Failed)
         95 - compareECLFiles_flow+MOD4_GRP (Failed)
         96 - compareECLFiles_flow+MOD4_UDQ_ACTIONX (Failed)
         97 - compareECLFiles_flow+TEST_WSEGSICD (Failed)
Errors while running CTest
```

**Comment by alfbr** [comment] 2020-09-13 21:08
Thank you! I am able to reproduce. Actually, they all have multi-segment wells. I am afraid there is no easy fix for this, but I will try to investigate and come up with a suggested solution.

**Comment by blattms** [comment] 2020-11-16 08:21
The situation has gotten worse now on my machine:
```
44% tests passed, 69 tests failed out of 124

The following tests FAILED:
         27 - compareECLFiles_flow+SPE1CASE2_THERMAL (Failed)
         28 - compareECLFiles_flow+SPE1CASE2_THERMAL_WATVISC (Failed)
         29 - compareECLFiles_flow+SPE1CASE2_ROCK2DTR (Failed)
         31 - compareECLFiles_flow+SPE1CASE1_METRIC_VFP1 (Failed)
         34 - compareECLFiles_flow+SPE3CASE1 (Failed)
         36 - compareECLFiles_flow+SPE9_CP_GROUP (Failed)
         38 - compareECLFiles_flow+3D_MSW (Failed)
         39 - compareECLFiles_flow+2D_OILWATER_POLYMER (Failed)
         40 - compareECLFiles_flow+2D_POLYMER_INJECTIVITY (Failed)
         41 - compareECLFiles_flow+2D_THREEPHASE_POLY_HETER (Failed)
         42 - compareECLFiles_flow+SPE5CASE1 (Failed)
         43 - compareECLFiles_flow+3D_WECON (Failed)
         46 - compareECLFiles_flow+FAULTS_MODEL_1 (Failed)
         47 - compareECLFiles_flow+0_BASE_MODEL2 (Failed)
         48 - compareECLFiles_flow+0A1_GRCTRL_LRAT_ORAT_BASE_MODEL2_STW (Failed)
         49 - compareECLFiles_flow+0A1_GRCTRL_LRAT_ORAT_BASE_MODEL2_MSW (Failed)
         50 - compareECLFiles_flow+0A2_GRCTRL_LRAT_ORAT_GGR_BASE_MODEL2_STW (Failed)
         51 - compareECLFiles_flow+0A2_GRCTRL_LRAT_ORAT_GGR_BASE_MODEL2_MSW (Failed)
         52 - compareECLFiles_flow+0A3_GRCTRL_LRAT_LRAT_BASE_MODEL2_STW (Failed)
         53 - compareECLFiles_flow+0A3_GRCTRL_LRAT_LRAT_BASE_MODEL2_MSW (Failed)
         54 - compareECLFiles_flow+0A4_GRCTRL_LRAT_LRAT_GGR_BASE_MODEL2_STW (Failed)
         55 - compareECLFiles_flow+0A4_GRCTRL_LRAT_LRAT_GGR_BASE_MODEL2_MSW (Failed)
         56 - compareECLFiles_flow+1_MULTREGT_MODEL2 (Failed)
         57 - compareECLFiles_flow+UDQ_ACTIONX (Failed)
         58 - compareECLFiles_flow+UDQ_WCONPROD (Failed)
         61 - compareECLFiles_flow+UDQ_M1 (Failed)
         62 - compareECLFiles_flow+UDQ_M2 (Failed)
         63 - compareECLFiles_flow+UDQ_M3 (Failed)
         64 - compareECLFiles_flow+2_MULTXYZ_MODEL2 (Failed)
         65 - compareECLFiles_flow+3_MULTFLT_MODEL2 (Failed)
         66 - compareECLFiles_flow+4_MINPVV_MODEL2 (Failed)
         67 - compareECLFiles_flow+5_SWATINIT_MODEL2 (Failed)
         68 - compareECLFiles_flow+6_ENDSCALE_MODEL2 (Failed)
         69 - compareECLFiles_flow+7_HYSTERESIS_MODEL2 (Failed)
         70 - compareECLFiles_flow+8_MULTIPLY_TRANXYZ_MODEL2 (Failed)
         71 - compareECLFiles_flow+9_EDITNNC_MODEL2 (Failed)
         72 - compareECLFiles_flow+9_1A_DEPL_MAX_RATE_MIN_BHP_STW (Failed)
         73 - compareECLFiles_flow+9_1A_DEPL_MAX_RATE_MIN_BHP_MSW (Failed)
         74 - compareECLFiles_flow+9_1B_DEPL_MAX_RATE_MIN_THP_STW (Failed)
         75 - compareECLFiles_flow+9_1B_DEPL_MAX_RATE_MIN_THP_MSW (Failed)
         76 - compareECLFiles_flow+9_2A_DEPL_GCONPROD_1L_STW (Failed)
         77 - compareECLFiles_flow+9_2A_DEPL_GCONPROD_1L_MSW (Failed)
         78 - compareECLFiles_flow+9_2B_DEPL_GCONPROD_2L_STW (Failed)
         79 - compareECLFiles_flow+9_2B_DEPL_GCONPROD_2L_MSW (Failed)
         80 - compareECLFiles_flow+9_3A_GINJ_REIN-G_STW (Failed)
         81 - compareECLFiles_flow+9_3A_GINJ_REIN-G_MSW (Failed)
         82 - compareECLFiles_flow+9_3B_GINJ_GAS_EXPORT_STW (Failed)
         83 - compareECLFiles_flow+9_3B_GINJ_GAS_EXPORT_MSW (Failed)
         84 - compareECLFiles_flow+9_3C_GINJ_GAS_GCONSUMP_STW (Failed)
         85 - compareECLFiles_flow+9_3C_GINJ_GAS_GCONSUMP_MSW (Failed)
         86 - compareECLFiles_flow+9_3D_GINJ_GAS_MAX_EXPORT_STW (Failed)
         87 - compareECLFiles_flow+9_3D_GINJ_GAS_MAX_EXPORT_MSW (Failed)
         88 - compareECLFiles_flow+9_3E_GAS_MIN_EXPORT_STW (Failed)
         89 - compareECLFiles_flow+9_3E_GAS_MIN_EXPORT_MSW (Failed)
         90 - compareECLFiles_flow+9_4A_WINJ_MAXWRATES_MAXBHP_GCONPROD_1L_STW (Failed)
         91 - compareECLFiles_flow+9_4A_WINJ_MAXWRATES_MAXBHP_GCONPROD_1L_MSW (Failed)
         92 - compareECLFiles_flow+9_4B_WINJ_VREP-W_STW (Failed)
         93 - compareECLFiles_flow+9_4B_WINJ_VREP-W_MSW (Failed)
         94 - compareECLFiles_flow+9_4C_WINJ_GINJ_VREP-W_REIN-G_STW (Failed)
         95 - compareECLFiles_flow+9_4C_WINJ_GINJ_VREP-W_REIN-G_MSW (Failed)
         96 - compareECLFiles_flow+9_4D_WINJ_GINJ_GAS_EXPORT_STW (Failed)
         97 - compareECLFiles_flow+9_4D_WINJ_GINJ_GAS_EXPORT_MSW (Failed)
         98 - compareECLFiles_flow+MOD4_GRP (Failed)
         99 - compareECLFiles_flow+MOD4_UDQ_ACTIONX (Failed)
        100 - compareECLFiles_flow+1_MSW_MODEL6 (Failed)
        101 - compareECLFiles_flow+TEST_WSEGSICD (Failed)
        103 - compareECLFiles_flow+SPE1FOAM (Failed)
        104 - compareECLFiles_flow+BC_LAB (Failed)
        106 - compareECLFiles_flow+COMPL_SMRY (Failed)
Errors while running CTest
```

**Comment by alfbr** [comment] 2020-11-16 12:16
Thanks for reporting! I believe this is caused by the new numerical defaults that are now in place. Now that the updated numerical defaults are in master, it is time to revisit this problem. I plan to make an attempt the coming two weeks.

**Comment by blattms** [comment] 2021-12-03 13:57
Seems to workl now (at least when using debian stable with system DUNE packages)

**Closed by blattms** 2021-12-03 13:57 UTC
