### ISSUE TITLE
Phase densities not reported initially

### ISSUE THREAD

**Issue by alfbr** [OPM/opm-simulators#1058] opened 2017-02-15 13:52 UTC
GAS_DEN, WAT_DEN and OIL_DEN not reported initially, but for subsequent report steps.

**Comment by andlaus** [comment] 2017-02-15 14:06
is this for flow_ebos, flow_legacy or both?

**Comment by alfbr** [comment] 2017-02-15 14:12
Possibly both, but testing is on flow_ebos

**Comment by andlaus** [comment] 2017-02-15 14:29
okay. which deck did you use and where is this supposed to get written to? I could not find the string `GAS_DEN` in the ECL reference PRT file for Norne...

**Comment by alfbr** [comment] 2017-02-16 08:11
It is written to the restart file.

**Comment by babrodtk** [comment] 2017-02-22 09:33
Just created a PR that tries to address this: #1068 

The issue is that derived quantities are not dumped at all for the first report step, since they were not initialized until after the simulation had started in flow_legacy.

**Comment by andlaus** [comment] 2017-04-07 10:20
#1068 has been merged and the FIP is reported before the initial time step for the first time. closing.

**Closed by andlaus** 2017-04-07 10:20 UTC
