### ISSUE TITLE
Build failure frankenstein branch

### ISSUE THREAD

**Issue by nairr** [OPM/opm-simulators#909] opened 2016-11-11 14:22 UTC
I was trying to install flow_ebos from the frankenstein branch and the following changes were required to successfully build opm-simulators and install flow_ebos:

 * It was required to remove `sol.sdc = &reservoir`; (line 108)  from Compat.hpp 

 * Convert `#include` statements used in various files pointing to the ewoms directory (eg. `#include <ewoms/applications/ebos/eclproblem.hh>` in BlackoilModelEbos.hpp), to use absolute paths, in order to have a successful build

 * Branch used: totto82:frankenstein_fip_output 

Best,
Rohith

**Comment by atgeirr** [comment] 2016-11-11 14:36
The first point I think happened since that member was just removed in OPM/opm-output#132. The master branch was updated simultaneously, but not the frankenstein branch.

**Comment by andlaus** [comment] 2016-11-11 15:11
First of all: Thanks for testing!

> The master branch was updated simultaneously, but not the frankenstein branch.

ok, sounds like another master merge is required. hang tight.

> Convert #include statements used in various files pointing to the ewoms directory (eg. #include <ewoms/applications/ebos/eclproblem.hh> in BlackoilModelEbos.hpp), to use absolute paths, in order to have a successful build

that was changed with #908. maybe you updated your ewoms module, but forgot the frankenstein branch of opm-simulators?

> Branch used: totto82:frankenstein_fip_output

that explains it: that branch needs to be rebased in order to work out of the box. you can locally merge the current frankeinstein branch, though.

**Comment by andlaus** [comment] 2016-11-11 17:37
ok, with #911 the plain `frankenstein` branch should now work again. (@totto82's FIP output branch unfortunately is a different story.)

**Comment by nairr** [comment] 2016-11-13 12:52
@andlaus - I can confirm that the plain frankenstein branch builds successfully now, thanks! (on a sidenote -not sure if this is by design, but the flow_ebos executable is written by default to opm/opm-simulators/build/bin instead of usr/local/bin)

**Comment by andlaus** [comment] 2016-11-13 15:16
do you mean it's only in `../build/bin` after `make install` or after the build. the former  would be a build system bug, the latter is as it is supposed to be ;)

**Comment by nairr** [comment] 2016-11-14 08:21
after make install (CMAKE_INSTALL_PREFIX not user defined) it is only found in ../build/bin

**Comment by andlaus** [comment] 2016-11-14 10:26
ok, I hope #913 fixed it. could you please check?

**Comment by nairr** [comment] 2016-11-14 11:45
I'm afraid it is still not fixed.  Furthermore, flow_multisegment and flow_multisegment_mpi as well exists exclusively in ../build/bin

**Comment by andlaus** [comment] 2016-11-14 11:51
now I'm out of ideas what the cause could be (as far as I can see everything w.r.t. `flow_ebos` and `flow_legacy` is identical). does it work if you bulldoze your build directory and re-create it from scatch?

**Comment by andlaus** [comment] 2016-11-14 11:52
(the fact that `flow_multisegment` and `flow_multisegment_mpi` are not installed is to be expected. I'm not sure if this was done on purpose or not, though.)

**Comment by akva2** [comment] 2016-11-14 11:52
your fix is definitely the cure. the other binaries were never installed since they have never been lifted from experimental status.

**Comment by nairr** [comment] 2016-11-14 11:58
Well, I did remove and re-create my build directory

**Comment by atgeirr** [comment] 2016-11-14 12:01
> (the fact that flow_multisegment and flow_multisegment_mpi are not installed is to be expected. I'm not sure if this was done on purpose or not, though.)

They were (are) considered experimental, and therefore not added to the install list.

**Comment by akva2** [comment] 2016-11-14 12:09
i'm "sorry" @nairr but i just confirmed it works as it should. you have something stale.

**Comment by andlaus** [comment] 2016-11-14 12:20
@nairr: maybe you forgot to update your clone from github after #913 was merged?

**Comment by nairr** [comment] 2016-11-14 12:30
my bad, I'll check up what's going wrong here. Good to know things are as they are supposed to be.

**Closed** 2016-11-17 15:46 UTC
