### ISSUE TITLE
Problems with reading the PERM fields in OPM

### ISSUE THREAD

**Issue by dlmorenob** [OPM/opm-simulators#746] opened 2016-06-28 22:59 UTC
I have been trying to run the Brugge model for research purposes and I guess I found something out which looks very strange.  I guess there is a problem when reading  the permeability files within OPM.  If you run the DATAFILE in Eclipse, it will run ok and you can use Resinsight to view the properties, they all look correct.  However, if you try running the same DATAFILE in OPM, you will notice on the EGRID file that the PERMX, PERMY and PERMZ tensors are wrong.  I think the routine for reading the PERM files is reading the coordinates wrongly.  I attach photos for you to see the result.  The same can be seen with Norne as you download it from the OPM-DATA-MASTER repository.

![wrong_models](https://cloud.githubusercontent.com/assets/9252709/16435226/075f5a88-3d5a-11e6-9517-e1b3cd3cd7cd.png)

Am I doing something wrong?

David

**Comment by joakim-hove** [comment] 2016-06-29 05:19
> Am I doing something wrong?

I can not really see how you can do anything wrong, so this looks like a nasty bug in OPM. Since we have verified the numerical results on Norne to quite high precision I just can't believe that the problem is in the reading stage[1], output on the other hand is a lot less mature, so my hope and belief is that this is really a bug in the output - we will certainly look into it.

Questions:

1. Are you using the binary packages or have you compiled from source?
2. Have you also looked on the `PORO` and `PORV` fields?




[1]: Iff the problem is actually in the reading phase, that would be a very potent demonstration of the power of boundary conditions - and a quite disconcerting result for all of history matching; I just can not believe things are that bad.

**Comment by dlmorenob** [comment] 2016-06-29 11:54
Answers:

1. I am compiling from source.  The version I am using is the one from June 15 2016.  However, It would be nice to mention that I have seen this problem since some time ago. 

2. The PORO and PORV fields look ok.

Also, I tried running the SPE10 case, the small version, and I do not know whether the perm should like this or not.  But I guess in this case the output was correct.  I ran both grids cartesian and corner point and they both look the same.  It is very strange.

 
![spe10](https://cloud.githubusercontent.com/assets/9252709/16450868/2e3a2992-3dc5-11e6-9912-d2c01e8a1067.png)

**Comment by atgeirr** [comment] 2016-06-29 12:50
A hypothesis (untested): I and J indexing got mixed up somehow (the Norne plot looks like that), perhaps only for fields (like perm) that have multiple entries per cell. Could that be it?

**Comment by dlmorenob** [comment] 2016-06-29 13:01
I did some tests on Monday trying to change the PERM patterns in Octave and did not manage to reproduce the pattern shown.  I will try again later today and let you know if I managed.  I guess, maybe it has to do with the fact that both models came from Petrel and ready to run in Eclipse. So as you know, the j index changes and when reading on OPM (just a theory) something gets really wrong.  Btw.  I wanted to ask and confirm,  does OPM uses the Eclipse standard for the axis? I mean, positive j downwards as well? I guess DUNE does it as PETREL does?

**Comment by joakim-hove** [comment] 2016-06-29 13:23
> A hypothesis (untested): I and J indexing got mixed up somehow (the Norne plot looks like that)

I also thought of that - it is on the list to look into.

**Comment by bska** [comment] 2016-06-29 13:32
I don't know **what**, but something definitely changed in this area.  Sadly my window is rather big (5th October 2015 to 29th June 2016), but I'm seeing the following comparison in [ResInsight](http://resinsight.org).

### 2015-10-05
![2015-10-05-permx](https://cloud.githubusercontent.com/assets/1871438/16453848/9ab724fa-3e0e-11e6-9218-59f9387ab91a.png)

### 2016-06-29
![2016-06-29-permx](https://cloud.githubusercontent.com/assets/1871438/16453862/a6752724-3e0e-11e6-908d-805918039eca.png)

**Comment by pgdr** [comment] 2016-06-29 13:42
The statistics reported differs with about a factor of 2.  This could be a good measure for a regression test in the future.

**Comment by joakim-hove** [comment] 2016-06-29 20:05
OK - I think the problem has been with the mapping between active cells and "global" cells in the output of properties. The net result was that we just wrote the `nactive` first elements of the global poperty vectors to the `INIT` file. Observe that properties like `PERMX`and PORO` might very well have reasonable values also for the inactive cells - as was the case here.

**Comment by jokva** [comment] 2016-06-30 12:05
@bska @dlmorenob Does the patch in opm-output by @joakim-hove fix this for you?

**Comment by bska** [comment] 2016-06-30 12:10
> Does the patch in [OPM/opm-output#51] fix this for you?

I'll fire off a check a little later today.

**Comment by jokva** [comment] 2016-06-30 12:17
Excellent, appreciate it.

**Comment by dlmorenob** [comment] 2016-06-30 12:19
I'll update and check later on today as well.  Thanks. I'll let you know.

**Comment by bska** [comment] 2016-06-30 14:01
>> Does the patch in [OPM/opm-output#51] fix this for you?
>
> I'll fire off a check a little later today.

Looks much better now.  Here are some new comparison plots

---

### 2015-10-05
![2015-10-05-permx](https://cloud.githubusercontent.com/assets/1871438/16453848/9ab724fa-3e0e-11e6-9218-59f9387ab91a.png)

### 2016-06-30
![2016-06-30-permx](https://cloud.githubusercontent.com/assets/1871438/16490843/a4150058-3edb-11e6-9cb8-36f6fc74526b.png)

**Comment by pgdr** [comment] 2016-06-30 14:19
Still some big differences in the statistical analysis, though.  Mean is 290&nbsp;vs&nbsp;390, and P90 is 772&nbsp;vs&nbsp;992.

**Comment by dlmorenob** [comment] 2016-07-04 02:17
I ran the case using OPM and Eclipse with the patch on and the results are alike, it looks fine to me.  Statistics are the same.  Thanks.  
![screenshot from 2016-07-03 21 15 19](https://cloud.githubusercontent.com/assets/9252709/16549314/7f850a64-4163-11e6-8bc1-3bb59c09491a.png)

**Comment by atgeirr** [comment] 2016-07-04 07:28
Excellent! I'll close this as resolved. Thanks @dlmorenob for the bug report and testing, and thanks to @joakim-hove @jokva @bska @pgdr for fixing and testing.

**Closed by atgeirr** 2016-07-04 07:28 UTC

**Comment by bska** [comment] 2016-07-04 07:49
> I ran the case using OPM and Eclipse with the patch on and the results are alike, it looks fine to me.

Both of those cases are named "BASE_CASE_OPM".  Is that just a coincidence or did you use the same data twice?

**Comment by dlmorenob** [comment] 2016-07-04 15:51
Its a copy/paste for the same Datafile, two directories.  The Eclipse Run is on the left and the OPM one on the right.

**Comment by bska** [comment] 2016-07-04 15:56
> Its a copy/paste for the same Datafile, two directories. The Eclipse Run is on the left and the OPM one on the right.

Excellent!  Thanks a lot for the information and testing.  I'd say the issue is resolved then.  Please do let us know if you see any other artifacts.
