### ISSUE TITLE
Single phase WATER model not running

### ISSUE THREAD

**Issue by EdmundStephens** [OPM/opm-simulators#3970] opened 2022-07-05 16:52 UTC
[2022.10] (Reposted from the TEMPI discussion)

The attached model has only WATER phase defined, which runs in Eclipse but gives the following error in Flow:

> No suitable configuration found, valid are Twophase, polymer, foam, brine, solvent, energy, and blackoil.

[WATER1_ECL.zip](https://github.com/OPM/opm-simulators/files/9048132/WATER1_ECL.zip)
[WATER1_FLOW.zip](https://github.com/OPM/opm-simulators/files/9048133/WATER1_FLOW.zip)

**Comment by bska** [comment] 2022-07-05 19:11
> [2022.10] (Reposted from the [TEMPI discussion](https://github.com/OPM/opm-simulators/issues/3969))

Hi Edmund,

Just for clarity: When you say "2022.10", do you really mean "2021.10"?  For what it's worth the `.DBG` transcript file from `WATER1_FLOW.zip` has the following header

> ```
> ########  #          ######   #           #
> #         #         #      #   #         # 
> #####     #         #      #    #   #   #  
> #         #         #      #     # # # #   
> #         #######    ######       #   #    
>
> Flow is a simulator for fully implicit three-phase black-oil flow, and is part of OPM.
> For more information visit: https://opm-project.org 
> 
> Flow Version     =  2021.10 ()
> ```

which does at least suggest that you're running the 2021.10 release instead.  In that case the single-phase thermal fix OPM/opm-common#3069 will not be available in your Flow binary.  I'm away from my primary development machine at the moment but I'll try to reproduce your symptoms tomorrow morning my time unless anyone beats me to it.

**Comment by EdmundStephens** [comment] 2022-07-05 20:24
Ha! You busted my time machine … indeed I am running 2021.10 (sorry)

**Comment by goncalvesmachadoc** [comment] 2022-07-06 06:05
Hi, for the version 2021.10, the single-version would not run with flow executable. There was a separate executable flow_onephase_energy that needed to be compiled. For the release 2022.4, everything was combined. There are two examples running ok with current flow executable: opm-tests/spe1/SPE1CASE1_WATER.DATA and opm-tests/spe1/SPE1CASE2_THERMAL_ONEPHASE.DATA

**Comment by OPMUSER** [comment] 2022-07-06 06:13
I ran using 2022-04 and master and had same problem as @EdmundStephens

**Comment by goncalvesmachadoc** [comment] 2022-07-06 08:35
I found  a bug with the output requested WBP. It depends on oil phase, which is not present: 

```
          if (this->wbpData_.count(cartesianIdx) > 0)
                this->wbpData_[cartesianIdx] = getValue(fs.pressure(oilPhaseIdx));
```

Second issue is related to group control keywords: 
![image](https://user-images.githubusercontent.com/54812829/177507165-dcab7cc5-47e4-4d67-bdc9-cf4caf225742.png)

By commenting out WBP and group related keywords I could run WATER1_Flow with release 2022.4.

**Comment by bska** [comment] 2022-07-06 08:41
> You busted my time machine … indeed I am running 2021.10 (sorry)

Nothing to apologise for&mdash;I'm just glad we got it cleared up.  It's not outside the realms of possibility however to be running 2022.10 however.  The current development sources identify as

> ```
> ########  #          ######   #           #
> #         #         #      #   #         # 
> #####     #         #      #    #   #   #  
> #         #         #      #     # # # #   
> #         #######    ######       #   #    
>
> Flow is a simulator for fully implicit three-phase black-oil flow, and is part of OPM.
> For more information visit: https://opm-project.org 
> 
> Flow Version     =  2022.10-pre (debug)
> ```

with the `-pre` tag suggesting in-development preview.  These are the sources that will become the 2022.10 release later this year&mdash;tentatively in October.  The `(debug)` suffix signifies a debug build of those sources.  In a release build there would typically be either a shortened commit hash or nothing at all.

@goncalvesmachadoc has [identified](https://github.com/OPM/opm-simulators/issues/3970#issuecomment-1175943557) the root cause of the problems here, namely that parts of the output reporting code blindly assumes that `OIL` is always active.  We'll fix that.

**Comment by OPMUSER** [comment] 2022-07-06 08:56
Also the group issue is that the target was liquid rate when there is only water in the model. Changing to water rate fixed 
the group issue, so this works.
```
GCONPROD
-- --	Group 	Cntl	^Oil	^Wat	^Gas	^Liq	Work	Limit
-- --	name  	mode	b/d	b/d	Mcf/d	b/d	over	rate
	FIELD	 WRAT	1*	  1600	 1*	1*  	RATE		/
/
```
Can we check for that as well?

I did try this and it still failed originally because of the WBP was still present - no way to find that error without a debugger.

**Comment by goncalvesmachadoc** [comment] 2022-07-06 09:16
Bug fixed in https://github.com/OPM/opm-simulators/pull/3971

**Comment by EdmundStephens** [comment] 2022-07-06 12:56
This runs with 2022.04 which I just installed. (Thank you for your hard work pulling this together!)

As you noted a couple of minor snafus you might add to your list of developments:
* WBP causes a problem ... suggest at least ignore this, but preferably can this keyword be implemented as it represents the other wise of the well inflow model drawdown as opposed to larger scale reservoir depletion. 
* GCONPROD needed to be defined as a max WATER rate ... suggest at least ignore any inapplicable rates, e.g. max OIL or GAS. For LIQUID maybe this should default to the WATER rate unless otherwise specified ??

Issue closed it seems to me.

**Comment by OPMUSER** [comment] 2022-11-02 06:03
@goncalvesmachadoc I get a regression failure with the current master, which will also be in the 2022-10 release. I changed GCONPROD to WRAT:

```
-- Constraints
GCONPROD
--	Group 	Cntl	^Oil	^Wat	^Gas	^Liq	Work	Limit
--	name  	mode	b/d	b/d	Mcf/d	b/d	over	rate
	FIELD		WRAT	1*	1*	1*	16000	RATE		/
/
```
I now I get this:

```
Starting time step 0, stepsize 3 days, at day 1/31, date = 02-Jan-2020
flow: /home/david/OPM/GitHub/opm-simulators/opm/simulators/wells/TargetCalculator.cpp:78: RateType Opm::WellGroupHelpers::TargetCalculator::calcModeRateFromRates(const RateType*) const [with RateType = double]: Assertion `pu_.phase_used[BlackoilPhases::Liquid]' failed.
[david-VirtualBox:05065] *** Process received signal ***
[david-VirtualBox:05065] Signal: Aborted (6)
[david-VirtualBox:05065] Signal code:  (-6)
[david-VirtualBox:05065] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f40e563a520]
[david-VirtualBox:05065] [ 1] /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c)[0x7f40e568ea7c]
[david-VirtualBox:05065] [ 2] /lib/x86_64-linux-gnu/libc.so.6(raise+0x16)[0x7f40e563a476]
[david-VirtualBox:05065] [ 3] /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3)[0x7f40e56207f3]
[david-VirtualBox:05065] [ 4] /lib/x86_64-linux-gnu/libc.so.6(+0x2871b)[0x7f40e562071b]
[david-VirtualBox:05065] [ 5] /lib/x86_64-linux-gnu/libc.so.6(+0x39e96)[0x7f40e5631e96]
[david-VirtualBox:05065] [ 6] /home/david/OPM/GitHub/opm-simulators/build/bin/flow(+0x25de385)[0x563fd919b385]
[david-VirtualBox:05065] [ 7] /home/david/OPM/GitHub/opm-simulators/build/bin/flow(+0x1d4d9e7)[0x563fd890a9e7]
[david-VirtualBox:05065] [ 8] /home/david/OPM/GitHub/opm-simulators/build/bin/flow(+0x2601361)[0x563fd91be361]
[david-VirtualBox:05065] [ 9] /home/david/OPM/GitHub/opm-simulators/build/bin/flow(+0x26015f8)[0x563fd91be5f8]
[david-VirtualBox:05065] [10] /home/david/OPM/GitHub/opm-simulators/build/bin/flow(+0x1d87cb3)[0x563fd8944cb3]
[david-VirtualBox:05065] [11] /home/david/OPM/GitHub/opm-simulators/build/bin/flow(+0x168b7d4)[0x563fd82487d4]
[david-VirtualBox:05065] [12] /home/david/OPM/GitHub/opm-simulators/build/bin/flow(+0x168bc7e)[0x563fd8248c7e]
[david-VirtualBox:05065] [13] /home/david/OPM/GitHub/opm-simulators/build/bin/flow(+0x16c102b)[0x563fd827e02b]
[david-VirtualBox:05065] [14] /home/david/OPM/GitHub/opm-simulators/build/bin/flow(+0x16c19af)[0x563fd827e9af]
[david-VirtualBox:05065] [15] /home/david/OPM/GitHub/opm-simulators/build/bin/flow(+0x16c9fbb)[0x563fd8286fbb]
[david-VirtualBox:05065] [16] /home/david/OPM/GitHub/opm-simulators/build/bin/flow(+0x16cc608)[0x563fd8289608]
[david-VirtualBox:05065] [17] /home/david/OPM/GitHub/opm-simulators/build/bin/flow(+0x16cf55d)[0x563fd828c55d]
[david-VirtualBox:05065] [18] /home/david/OPM/GitHub/opm-simulators/build/bin/flow(+0x16d05fb)[0x563fd828d5fb]
[david-VirtualBox:05065] [19] /home/david/OPM/GitHub/opm-simulators/build/bin/flow(+0x16bed2e)[0x563fd827bd2e]
[david-VirtualBox:05065] [20] /home/david/OPM/GitHub/opm-simulators/build/bin/flow(+0x1638301)[0x563fd81f5301]
[david-VirtualBox:05065] [21] /home/david/OPM/GitHub/opm-simulators/build/bin/flow(+0x275985)[0x563fd6e32985]
[david-VirtualBox:05065] [22] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7f40e5621d90]
[david-VirtualBox:05065] [23] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7f40e5621e40]
[david-VirtualBox:05065] [24] /home/david/OPM/GitHub/opm-simulators/build/bin/flow(+0x397155)[0x563fd6f54155]
[david-VirtualBox:05065] *** End of error message ***
Aborted (core dumped)
Process Complete (0) 
```
Deck attached.



[WATER1_FLOW_FIXED.zip](https://github.com/OPM/opm-simulators/files/9916746/WATER1_FLOW_FIXED.zip)

**Comment by OPMUSER** [comment] 2022-11-02 07:26
Close, data entry error  - case runs with WRAT and correct water rate.

**Closed by OPMUSER** 2022-11-02 07:26 UTC
