### ISSUE TITLE
No viscosities in output

### ISSUE THREAD

**Issue by alfbr** [OPM/opm-simulators#1061] opened 2017-02-16 08:35 UTC
Currently we have no output for viscosities. The viscosities are expected in the restart file, with the keywords OIL_VISC, WAT_VISC and GAS_VISC.

**Comment by dr-robertk** [comment] 2017-02-16 10:09
It's in the code in opm-simulators,SimulatorFullyImplicitBlackoilOutput.hpp line 500.... So there must be a problem either with the rstKeywords["DEN"] or some problem further down the line.

**Comment by babrodtk** [comment] 2017-02-22 09:54
I cannot reproduce this directly. If I e.g., run norne with 
```
RPTRST
VISC /
```
I do get 'GAS_VISC' / 'OIL_VISC' / 'WAT_VISC' in the UNRST (convertd to FUNRST)-file. 

However, if I run with
```
RPTRST
ALLPROPS /
```
I do not get the expected viscosities. This should have triggered the correct output, and I'll investigate a bit to see what's missing here.

If I run with 
```
RPTRST
VOIL VGAS VWAT / 
```
I do not get the viscosities eighter in output (though these are E300 keywords I believe). 

Do you know which keyword was used to try to trigger the output?

**Comment by atgeirr** [comment] 2017-02-23 14:28
This should now be fixed, closing.

**Closed by atgeirr** 2017-02-23 14:28 UTC
