### ISSUE TITLE
compilation error with dune 2.7/master 

### ISSUE THREAD

**Issue by hnil** [OPM/opm-simulators#2095] opened 2019-10-22 11:04 UTC
Compilation is done with dune master/2.7 installed (needed fix in dune master). Also this compilation have most dune modules available.
Part of error meassage is:
```
/home/hnil/Documents/GITHUB/OPM/opm_source/devel_swift/opm-simulators/ebos/collecttoiorank.hh:336:63: error: no matching function for call to ‘Opm::CollectDataToIORank<Opm::EclCpGridVanguard<Opm::Properties::TTag::EbosTypeTag> >::ElementIndexScatterHandle<Dune::MultipleCodimMultipleGeomTypeMapper<Dune::GridView<Dune::DefaultLeafGridViewTraits<Dune::CpGrid> >, Dune::Impl::MCMGFailLayout> >::ElementIndexScatterHandle(EquilElementMapper&, ElementMapper&, std::vector<int>&)’
                 ElementIndexScatterHandle<EquilElementMapper> handle(equilElemMapper, elemMapper, localIdxToGlobalIdx_);
                                                               ^~~~~~
/home/hnil/Documents/GITHUB/OPM/opm_source/devel_swift/opm-simulators/ebos/collecttoiorank.hh:214:9: note: candidate: ‘Opm::CollectDataToIORank<Vanguard>::ElementIndexScatterHandle<Mapper>::ElementIndexScatterHandle(const Mapper&, const Mapper&, std::vector<int>&) [with Mapper = Dune::MultipleCodimMultipleGeomTypeMapper<Dune::GridView<Dune::DefaultLeafGridViewTraits<Dune::CpGrid> >, Dune::Impl::MCMGFailLayout>; Vanguard = Opm::EclCpGridVanguard<Opm::Properties::TTag::EbosTypeTag>]’
         ElementIndexScatterHandle(const Mapper& sendMapper, const Mapper& recvMapper, std::vector<int>& elementIndices)
         ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/hnil/Documents/GITHUB/OPM/opm_source/devel_swift/opm-simulators/ebos/collecttoiorank.hh:214:9: note:   no known conversion for argument 2 from ‘ElementMapper’ {aka ‘Dune::MultipleCodimMultipleGeomTypeMapper<Dune::GridView<Dune::Fem::GridPart2GridViewTraits<Dune::Fem::AdaptiveLeafGridPart<Dune::CpGrid, (Dune::PartitionIteratorType)4, false> > >, Dune::Impl::MCMGFailLayout>’} to ‘const Dune::MultipleCodimMultipleGeomTypeMapper<Dune::GridView<Dune::DefaultLeafGridViewTraits<Dune::CpGrid> >, Dune::Impl::MCMGFailLayout>&’
/home/hnil/Documents/GITHUB/OPM/opm_source/devel_swift/opm-simulators/ebos/collecttoiorank.hh:211:11: note: candidate: ‘Opm::CollectDataToIORank<Opm::EclCpGridVanguard<Opm::Properties::TTag::EbosTypeTag> >::ElementIndexScatterHandle<Dune::MultipleCodimMultipleGeomTypeMapper<Dune::GridView<Dune::DefaultLeafGridViewTraits<Dune::CpGrid> >, Dune::Impl::MCMGFailLayout> >::ElementIndexScatterHandle(const Opm::CollectDataToIORank<Opm::EclCpGridVanguard<Opm::Properties::TTag::EbosTypeTag> >::ElementIndexScatterHandle<Dune::MultipleCodimMultipleGeomTypeMapper<Dune::GridView<Dune::DefaultLeafGridViewTraits<Dune::CpGrid> >, Dune::Impl::MCMGFailLayout> >&)’
     class ElementIndexScatterHandle
           ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/hnil/Documents/GITHUB/OPM/opm_source/devel_swift/opm-simulators/ebos/collecttoiorank.hh:211:11: note:   candidate expects 1 argument, 3 provided
/home/hnil/Documents/GITHUB/OPM/opm_source/devel_swift/opm-simulators/ebos/collecttoiorank.hh:211:11: note: candidate: ‘Opm::CollectDataToIORank<Opm::EclCpGridVanguard<Opm::Properties::TTag::EbosTypeTag> >::ElementIndexScatterHandle<Dune::MultipleCodimMultipleGeomTypeMapper<Dune::GridView<Dune::DefaultLeafGridViewTraits<Dune::CpGrid> >, Dune::Impl::MCMGFailLayout> >::ElementIndexScatterHandle(Opm::CollectDataToIORank<Opm::EclCpGridVanguard<Opm::Properties::TTag::EbosTypeTag> >::ElementIndexScatterHandle<Dune::MultipleCodimMultipleGeomTypeMapper<Dune::GridView<Dune::DefaultLeafGridViewTraits<Dune::CpGrid> >, Dune::Impl::MCMGFailLayout> >&&)’
/home/hnil/Documents/GITHUB/OPM/opm_source/devel_swift/opm-simulators/ebos/collecttoiorank.hh:211:11: note:   candidate expects 1 argument, 3 provided
```

**Comment by blattms** [comment] 2019-10-22 11:35
Will cook up a fix. But you need to test since I do not use dune-fem currently.

**Comment by blattms** [comment] 2019-10-22 13:19
Please try #2098

**Comment by blattms** [comment] 2019-10-24 10:53
How do I replicate the error?

**Comment by GitPaean** [comment] 2019-10-24 10:56
I think you fixed it through #2098.

**Comment by GitPaean** [comment] 2019-10-24 10:57
> How do I replicate the error?

You try to compile flow with master branch of dune with dune-fem.

**Comment by blattms** [comment] 2019-10-24 11:32
#2098 is neither merged nor backported to the release. I am currently testing compiling the release together with dune-fem and not seeing the problem. Either I am doing something wrong or I would need
additional code to trigger it.

**Comment by GitPaean** [comment] 2019-10-24 13:07
I tested it again with the master branch, without #2098, the reported error messages were reproduced on my computer.

**Closed** 2019-10-24 13:16 UTC
